### ISSUE TITLE
[feature suggestion] ability to filter by one of the link params

### ISSUE THREAD

**Issue by jbtheard** [steven-tey/dub#100]
As a marketer, I may need to build multiple links for the same target.

Would be good to be able to quickly identify all links targeting the same url (and get analytics on this group).

Same applies for a specific campaign or possibly one of the other fields available.

**Comment by steven-tey** [comment]
I believe this can be achieved via our new Tags feature: https://dub.sh/changelog/introducing-tags

Going to close this for now, but feel free to reopen if needed! :)
