### ISSUE TITLE
[feature suggestion] tags

### ISSUE THREAD

**Issue by jbtheard** [steven-tey/dub#101]
I'd love to be able to add tags to each link so that I could either filter via tags, and even get analytics at tag level.

**Comment by steven-tey** [comment]
Was just discussing this in this PR: https://github.com/steven-tey/dub/pull/94#issuecomment-1302892552

Will definitely be cool to get analytics at tag level too! Thanks for the suggestion!

**Comment by steven-tey** [comment]
Whoops, forgot to follow up here – Tags are now live! :)

https://dub.sh/changelog/introducing-tags
