### ISSUE TITLE
[feature suggestion] wizard to create multiple links targeting same url

### ISSUE THREAD

**Issue by jbtheard** [steven-tey/dub#102]
as a marketer, I sometimes want to generate multiple links for a campaign targeting a single page, but across different platform.

Instead of having to use the new link form n times I'd rather select my platforms in a multi select and fill the target url in a second step. That would in turn create n links.

**Comment by jbtheard** [comment]
And a lot of people already for such services :)

**Comment by steven-tey** [comment]
Hey @jbtheard! This feature is now live: https://github.com/steven-tey/dub/pull/120 🥳 

Feel free to try it out and let me know what you think!

**Comment by jbtheard** [comment]
Seems to work like a charm; good UX and quick execution. Thank you!
