### ISSUE TITLE
Question: Can I use custom domain with existing website?

### ISSUE THREAD

**Issue by max-programming** [steven-tey/dub#103]
I was exploring the custom domain part. Can I use it with [my domain name](https://usmans.me) which is already in use for my personal site?

Then whenever someone visits `usmans.me/[slug]` they get redirected.

**Comment by steven-tey** [comment]
You can't use it with an existing site since it'll result in a domain conflict, but you can use it with a subdomain (e.g. `l.usmans.me` or `link.usmans.me`) 😄

**Comment by max-programming** [comment]
That's good! Thanks for the answer 😃
