### ISSUE TITLE
Sign up isn't sending an email

### ISSUE THREAD

**Issue by IzMichael** [steven-tey/dub#107]
Hiya, apologies if this isn't the right place for this.

I'm trying to sign up on the [app.dub.sh/register](https://app.dub.sh/register) page, but I'm not receiving an email despite seeing the "Email sent" message.
![image](https://user-images.githubusercontent.com/57115702/200264211-c836e217-5a04-4400-8dbd-62389fc59882.png)

I've tried to sign up with two different emails, one `@outlook.com` and one with a custom domain, and neither have worked. I tried this yesterday as well as today, and still not received any email.

**Comment by ps-89** [comment]
@IzMichael For a custom domain, it's working for me.

**Comment by IzMichael** [comment]
Huh, odd. I've tried again today, but it's still not working...

**Comment by steven-tey** [comment]
hey @IzMichael, apologies for that! I just checked our Postmark logs and looks like your email provider marked `dub.sh` as spam 😕 can you maybe try checking your spam folder?

**Comment by IzMichael** [comment]
I've just tried again, after fully disabling my spam filter and I've whitelisted `*@dub.sh`, and I'm still not receiving any emails.

**Comment by IzMichael** [comment]
Fixed on the Slack; was an issue with my email provider.
