### ISSUE TITLE
My all links got wiped out after sometime 

### ISSUE THREAD

**Issue by Muzzthecoder** [steven-tey/dub#108]
Hi there! I have been using Dub for over a month now and for some reason all my links got wiped out the other day. They redirected to the [homepage](https://dub.sh) 

For example this link https://dub.sh/QAmwGY5 doesn't work anymore.

**Comment by Muzzthecoder** [comment]
My email I used to log in is muzzthecoder@gmail.com

**Comment by steven-tey** [comment]
That's odd! I was [removing some phishing links](https://twitter.com/steventey/status/1589329847091748864) the other day and it might've affected your links somehow. What's the link that you were redirecting to? Also were these public links (those get auto-deleted after 15 mins)?

**Comment by Muzzthecoder** [comment]
Actually it was redirected to my latest article on Hashnode. https://muzzammil.hashnode.dev/setup-kali-linux-like-a-pro

**Comment by max-programming** [comment]
@Muzzthecoder Did you add any links like these?
![image](https://user-images.githubusercontent.com/51731966/201264560-8ae2289c-55ac-4c0a-9370-3058479ce055.png)

**Comment by Muzzthecoder** [comment]
Nope

**Comment by steven-tey** [comment]
Was it a public link? (did you add it via https://dub.sh) or did you add it from the app?

In any case, can you try re-adding the link with the same key? This seems to be an isolated incident so I'm going to go ahead and close this issue for now – sorry again for the inconvenience!

**Comment by Muzzthecoder** [comment]
@steven-tey Now I got it, how to do it and also it is working cool 😇
