### ISSUE TITLE
dub.sh home page globe spikes GPU to 100%

### ISSUE THREAD

**Issue by stashymane** [steven-tey/dub#11]
![image](https://user-images.githubusercontent.com/4071883/191813323-31b28f84-9821-43ad-9917-230e5414b123.png)

The globe's canvas is set to 2000x2000 size regardless of my screen res (1080p), I don't think that's necessary.
Also perhaps a bit of optimization.

**Comment by steven-tey** [comment]
Looking into this, it looks like it could be related to the globe animation 🤔 

Related comment: https://github.com/shuding/cobe/issues/39#issuecomment-1228296175

**Comment by steven-tey** [comment]
This should be fixed by https://github.com/steven-tey/dub/pull/13 👍

**Comment by chris-pikul** [comment]
Just experienced this on Win11 & Chrome 105.0.5195.127 going to the domain, has this fix been pushed publicly?

Tab loads, then slows to a crawl, then stops all together. Locks up my browser, attempting to close the tab requires patience before Chrome nukes it and then systems back to operating fine.

**Comment by AnnleeFores** [comment]
Despite a slight improvement in performance, the website still lags.

Using Chrome 105.0.5195.127 and Firefox 105.0 on Windows 11. (64-bit)

**Comment by stashymane** [comment]
GPU is no longer at 90%, it's at 60% 😬
For context, games like CS:GO run my GPU at 40% :)

**Comment by BitesizedLion** [comment]
It no longer kills my browser entirely, but still has higher usage than what a homepage should (imo)

**Comment by steven-tey** [comment]
@chris-pikul @AnnleeFores @stashymane @BitesizedLion Okay y'all, I just pushed this commit that should optimize the globe for different device GPU cores: https://github.com/steven-tey/dub/commit/9518ca1b0a44554ca10b30018eb76d8880d3254a

Can you check and let me know if it's still blowing up your GPUs? 

If it is, can you go into Chrome console and enter `navigator.hardwareConcurrency` and tell me what value it returns?

**Comment by BitesizedLion** [comment]
Uses 30-35% on chrome
Uses 60% on firefox

![image](https://user-images.githubusercontent.com/42980888/191979826-3f0f9327-b5b3-44d3-897a-aaa23eb842e7.png)

**Comment by BitesizedLion** [comment]
Also isn't `navigator.hardwareConcurrency` for CPU?

**Comment by AnnleeFores** [comment]
![image](https://user-images.githubusercontent.com/10363107/191987220-4146b8b0-43da-4e6d-ba10-75db20883bde.png)

**Comment by georgejipa** [comment]
Tested on two PCs, both on Windows 11 Pro (64bit).

```
GPU: Integrated
navigator.hardwareConcurrency = 6
```
```
GPU: RTX 3050
navigator.hardwareConcurrency = 16
```

Almost the same behavior. As expected, the website is much more usable on the second PC.

**Comment by Gladson-Lalu** [comment]
I am still facing the same. Here is a SS
![Screenshot (454)](https://user-images.githubusercontent.com/60311559/192112462-f5ff5094-77ce-492e-8583-2e38c9eefd80.png)

**Comment by roman-koshchei** [comment]
Each time I visit the home page I delete the globe canvas. It helps a lot. I think the globe isn't necessary. Maybe make it optional to see?

**Comment by steven-tey** [comment]
Hey everyone! I just pushed [this PR](https://github.com/steven-tey/dub/pull/39) that adds a fallback video for devices that don't support WebGL – let me know if this helps!

**Comment by SaiyaDev** [comment]
> Hey everyone! I just pushed [this PR](https://github.com/steven-tey/dub/pull/39) that adds a fallback video for devices that don't have proper support for WebGL – let me know if this helps!

Hey, still same issue for me, my GPU runs at 5-10% usually when I open dub.sh it spikes up to 60%+ when I have the tab opened

**Comment by steven-tey** [comment]
This issue has been largely resolved so I'm going to close this for now!

Apologies again for the performance issues 🙏

**Comment by riccox** [comment]
To be honest, so far the homepage of this website is still too laggy on my chrome.
