### ISSUE TITLE
Add a character length warning to social custom previews `title` and `description` fields  

### ISSUE THREAD

**Issue by mfts** [steven-tey/dub#112]
If you exceed the character length for the `description` field in the social custom previews, it currently throws an alert-style error. 

Suggestions: add a character count with an upper limit (similar to Twitter)

<img width="389" alt="Screenshot 2022-11-10 at 19 48 26" src="https://user-images.githubusercontent.com/4049052/201180928-9f66e07e-fdc1-4b59-96d3-5b7c6886942a.png">

I'm happy to work on this by end of this week.

**Comment by steven-tey** [comment]
This has since been fixed! https://github.com/steven-tey/dub/blob/main/lib/api/links.ts#L156-L157
