### ISSUE TITLE
[Feature] Set custom name or tags

### ISSUE THREAD

**Issue by DrummerB** [steven-tey/dub#124]
For better organizing and finding links, it would be nice to be able to set custom names, instead of just seeing the long and short links. E.g. Bitly reads the page title and uses that as the default name of the link, which can be changed later.

**Comment by steven-tey** [comment]
Related to #101 – it's on the roadmap as well! I actually was using the title instead of the long URL at first but resorted to the long URL for clarity. I believe the tags feature should solve this!

**Comment by steven-tey** [comment]
Whoops, forgot to follow up here – Tags are now live! :)

https://dub.sh/changelog/introducing-tags
