### ISSUE TITLE
Hashes are stripped from url before sharing

### ISSUE THREAD

**Issue by JeroenReumkens** [steven-tey/dub#133]
Hi there! 

I noticed that hashes are stripped from the url when sharing. I can imagine why you might do this, only downside is this prevents me from sharing TypeScript Playground links like this one: https://www.typescriptlang.org/play?#code/BIUwNmD2AEAmCuAjIA

The TypeScript playground encodes the content of the playground in the hash. And since they can get quite long, for me it feels like a great use case to use Dub for this 😅 

Let me know if you need more detail.

**Comment by steven-tey** [comment]
Will take a look at this, thanks for reporting!

**Comment by steven-tey** [comment]
It took me wayyy longer than expected, but I finally fixed this issue! Turns out it was a rookie mistake of not encoding the URL properly when it's created 😅 

Really sorry for the delay here!
