### ISSUE TITLE
License Doubt

### ISSUE THREAD

**Issue by Diogovski** [steven-tey/dub#136]
Hi, i have some questions regarding the license. So, I'm building a SaaS base on YouTube automation + analytics, and one of the features i wante to included was enabling users to create a custom link to the YouTube video uploaded ( either via my SaaS or from ghe normal YouTube dashboard), so for that i decided to build it around what you already accomplished ( dub ), but my question is, am i allowed to do it? Bc, i see a lot of open source projects that require you to open source if you're selling a service on top of it, but in my case i am modifying the original project, so yeah that's my question, so technically not an issue!

P.s When i deploy to vercel, on the .vercel.app domain it shows the page exactly like dub.sh but if i open it in my own domain it only shows the map of locations, i don't know why.

**Comment by steven-tey** [comment]
Hey Diogo, thanks for the question! According to the AGPLv3 license, If you make a derivative work of this, and distribute it or run it as a service on a server to others then you have to provide the source code under this license.

You can read more about it in this blog post by Plausible: https://plausible.io/blog/open-source-licenses

Also, regarding the bug you're facing, you probably will need to replace some of the hard-coded values here for it to work https://github.com/steven-tey/dub/blob/main/lib/constants/index.ts#L30-L35
