### ISSUE TITLE
Slugs prefixed with `api` throw 404

### ISSUE THREAD

**Issue by max-programming** [steven-tey/dub#139]
Whenever I create a slug starting with `api`, it gives a 404 page.

For eg:

https://dub.sh/api-tester-as
https://dub.sh/api-tester-ps
https://dub.sh/apigoogle

**Comment by steven-tey** [comment]
Great catch, this seems related to https://github.com/vercel/platforms/pull/166 – will fix!

**Comment by steven-tey** [comment]
This should be fixed!
