### ISSUE TITLE
Facing too much lag in this portion of the webpage

### ISSUE THREAD

**Issue by Deva-1903** [steven-tey/dub#145]
![Screenshot (5)](https://user-images.githubusercontent.com/97371915/214222466-59b04bb2-d236-462c-9c19-933c414a8eb6.png)

While moving around this part in the web page, there is too much lag in this portion. Try to make it smoother.

**Comment by steven-tey** [comment]
What computer are you on?

**Comment by Deva-1903** [comment]
> 

Lenovo Thinkpad T450

**Comment by steven-tey** [comment]
Ahh that makes sense – this animation uses quite a bit of GPU power unfortunately 😬 will think of ways to optimize it

**Comment by Deva-1903** [comment]
That's cool to here from you. Can I close this issue or let it be open? I would like to contribute to this project ( I am a beginner ) looking for any good first issues. I would like to join your community slack or discord channel ?

**Comment by steven-tey** [comment]
Gonna close it for now but feel free to make any PRs that could be helpful! :)
