### ISSUE TITLE
Unable to sign up

### ISSUE THREAD

**Issue by rileyjshaw** [steven-tey/dub#146]
The magic link portion of your site appears to be broken for creating a new account.

I went to https://app.dub.sh/register, entered my email address, and nothing arrived 🤔  I waited about 30 minutes just to be sure before logging this issue.

**Comment by steven-tey** [comment]
Hey @rileyjshaw! Thanks for reporting this – did you check your spam folder? The SMTP I use, Postmark is pretty good, but it sometimes land in the inevitable spam folder 😬 

I just tried signing up with a new account and it seems to work for me!

**Comment by rileyjshaw** [comment]
It’s not in my spam folder. I was sending it to a Fastmail account on a custom domain. The account is my main email address and definitely works.

Sending it to a plain gmail address seems to work.

**Comment by steven-tey** [comment]
Oh weird! I guess my email IP might've been blacklisted by Fastmail <picture data-single-emoji=":sad_praying_cowboy:" title=":sad_praying_cowboy:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..B8wctEVCN9BIXbpa.Ib9fzIHY9aUCdIjKMFMOcltR-gbI57NVrZ8YObIruF4wwJ-j8Y23HQYgr56FTeF9vMl_YZXjuh8pR3FN4il-74bhAd8jT70JEp4f7z6D4CcfYx6OAxGkOoYTbeMJbAuJXCxP.lPIVpZPh-IxRDNqLpsFHwA" alt=":sad_praying_cowboy:" align="absmiddle"></picture> thanks for the heads-up regardless!

**Comment by rileyjshaw** [comment]
That’s a shame 😞 let me know if there’s anything I can help test!

**Comment by steven-tey** [comment]
Thanks @rileyjshaw! Closing this for now since I'm not getting any other complaints about this – will look into adding more signup options in the future (e.g. Google OAuth) to avoid this issue! :)

**Comment by rileyjshaw** [comment]
I think I discovered what the issue was!!

I use NordVPN, and their Mac app has an added “Threat protection” feature. Turning that off solved the issue.

Writing it here in case anyone else encounters the same issue.
