### ISSUE TITLE
Auto-copy new link to clipboard

### ISSUE THREAD

**Issue by fmerian** [steven-tey/dub#149]
Currently, the user flow to copy a new link is:

1. From the dashboard, Click the `add` button
2. Add your destination URL
3. Set up your short URL
4. Click the `add link` button
5. Click on the icon to copy the short URL

Instead, we could simplify and remove step 5 by auto-copying short URL to clipboard.

**Comment by steven-tey** [comment]
Brilliant idea! Just implemented it :) 

https://user-images.githubusercontent.com/28986134/222050033-4b113d6f-4855-41e5-a5d0-72674f569fe7.mp4
