### ISSUE TITLE
links with parameters not working?

### ISSUE THREAD

**Issue by PeerRich** [steven-tey/dub#152]
we have this link https://go.cal.com/help-wanted which links to https://github.com/calcom/cal.com/issues?q=is:issue+is:open+sort:updated-desc+label:%22%F0%9F%99%8B%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8Fhelp+wanted%22

but instead it links to our fallback which is cal.com

**Comment by TimZolleis** [comment]
May that be related to https://github.com/steven-tey/dub/issues/153?

**Comment by steven-tey** [comment]
I [fixed](https://github.com/steven-tey/dub/commit/9ffc677c56b18bc10c682f6ae494d0a533c189d7) this issue! Turns out it was a rookie mistake of not encoding the URL properly when it's created 😅
