### ISSUE TITLE
Error that breaks the app when setting expiration date

### ISSUE THREAD

**Issue by 18jad** [steven-tey/dub#156]
So I was trying to set an expiry date, and this issue came up:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/74220144/224515050-60086e42-ac00-4a65-a365-7b179260a25c.png">

It happened when I selected a date from the calendar and then clicked on the year in the input field to change it using the keyboard, I typed 0 and the whole app crashed.

**Comment by steven-tey** [comment]
Thanks for reporting! I was able to repro this and just pushed up a fix for it: https://github.com/steven-tey/dub/commit/0c87a8a82a57efc63c415b49b10c78142de03c1f
