### ISSUE TITLE
Metathread for self-hosting

### ISSUE THREAD

**Issue by tomy0000000** [steven-tey/dub#161]
Here is a list of problems that might bump in your way when self-hosting dub.

- Stats not working: Tinybird should be setup #150
- Can not login: SMTP server is not configured #119
- Project can not be deleted: Cloudinary should be setup #162
- Table not found during deployment: Push database schema on local then deploy again #104 

For more details and progress on instructions on self-hosting docs, refer to #12

If all this stuff is too complicated for you, stay tuned for docker hosting options at #25 

Please comment to help complete this list.

**Comment by steven-tey** [comment]
Took a first stab at improving Dub's self-hosting experience today by:
- Adding detailed instructions on how to set up env vars in [`.env.example` file](https://github.com/steven-tey/dub/blob/main/.env.example)
- Added a [PR](https://github.com/steven-tey/dub/pull/331) that publishes all the Tinybird pipes that Dub uses

This is still not perfect, but it's a stop gap – we're planning to add a proper, well-documented self-hosting guide soon! Stay tuned! :)

**Comment by steven-tey** [comment]
Closing this in favor of #12 (we're getting close to a proper self-hosting experience for Dub!!)
