### ISSUE TITLE
Error when deleting projects on self-hosted instance

### ISSUE THREAD

**Issue by tomy0000000** [steven-tey/dub#162]
The following error raised when deleting a project on self-hosted instance.

```log
Must supply cloud_name
Must supply cloud_name
RequestId: 590ae8b8-8f73-4d89-b117-2a61563c521d Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

It seems that the error is coming from cloudinary SDK, how should I set this up?

**Comment by kalmndo** [comment]
just export CLOUDINARY_URL in your .env and you good to go.

**Comment by steven-tey** [comment]
@kalmndo is right! Sorry for the confusing experience here 😓
