### ISSUE TITLE
[Feature] Welcome page

### ISSUE THREAD

**Issue by fmerian** [steven-tey/dub#163]
- When I log into Dub, I land on `app.dub.sh`
- If I don't have any projects, I land on an empty page :/
- Instead, I'd prefer to land on `app.dub.sh/links`

**Comment by steven-tey** [comment]
We do have a welcome flow for new users when they first sign up: https://app.dub.sh/welcome 

But good point about this! We want to encourage folks to create projects though, so that's why we default to the projects tab 😄

**Comment by fmerian** [comment]
makes much sense. closing the issue for now, thanks. keep up your great work!
