### ISSUE TITLE
[Feature] Keyboard shortcuts

### ISSUE THREAD

**Issue by fmerian** [steven-tey/dub#164]
the simple UI makes Dub super fast to use.

so, I'd love to have keystrokes to do more quick actions. 

some ideas:
- Add new Dub link
- Open stats for selected link
- Archive a Dub link
- Move to next tab

**Comment by steven-tey** [comment]
Felt cute, pushed a PR that adds this feature: https://github.com/steven-tey/dub/pull/189

**Comment by steven-tey** [comment]
Shipped!! :)

**Comment by fmerian** [comment]
awesome, thanks! keep it up, @steven-tey!!
