### ISSUE TITLE
[Feature] Paste URL to customize OG image

### ISSUE THREAD

**Issue by fmerian** [steven-tey/dub#165]
when you want to add a custom social media card, your only option is to upload an image.

would like to paste a URL instead.

Also, can we specify max size is 1MB?

![Custom Social Media Card](https://user-images.githubusercontent.com/1890087/225897755-510e8283-403e-4d4e-811b-d20de72daf41.png)

**Comment by steven-tey** [comment]
Got too tired of not being a paste URL for images so decided to knock this one out 😛 

Sorry for the delay!
