### ISSUE TITLE
[Landing] menus in top nav bar

### ISSUE THREAD

**Issue by fmerian** [steven-tey/dub#168]
would be nice to have quick links in the top nav bar of the landing page

some suggestions from existing `id`:
- `Features` -- link to [#features](https://dub.sh/#features)
- `Pricing` -- link to [#pricing](https://dub.sh/#pricing)

![Dub - ATF Section](https://user-images.githubusercontent.com/1890087/227489804-9f2ea935-66aa-44a7-96f7-e420d1f682f3.png)

**Comment by steven-tey** [comment]
Added these with https://github.com/steven-tey/dub/pull/185 – will keep adding more in the coming weeks! Thank you!
