### ISSUE TITLE
[Feature] weekly/monthly reports

### ISSUE THREAD

**Issue by m-abdelwahab** [steven-tey/dub#172]
It would be cool if I could receive weekly/monthly reports that highlight the performance of my short links. It could be top 5-10 links

**Comment by fmerian** [comment]
absolutely *love* this idea, @m-abdelwahab! it completely makes sense, especially if you use Dub as a team.

how would you like to get these reports? email, Slack?
what stats would you like to have included? top links, locations, referrers, else?

then, how about a living dashboard you can access anytime? I really like the Typefully analytics dashboard, see example [here](https://typefully.com/linuz90/stats).

**Comment by m-abdelwahab** [comment]
Email can be a good start. Slack would be ideal since it provides visibility. Dashboards are cool, but they require logging into the platform.

**Comment by fmerian** [comment]
> Dashboards are cool, but they require logging into the platform.

do they? I was thinking about making stats public for anyone with the link. for the record, it currently works with Dub -- see example [here](https://dub.sh/stats/github).

![public-stats](https://user-images.githubusercontent.com/1890087/233058779-506e0b78-32a6-49b7-b2cf-ac35f236d3a5.png)

**Comment by m-abdelwahab** [comment]
Oh I didn't know about this! That's very cool

**Comment by m-abdelwahab** [comment]
To me a report would include the performance of several links

**Comment by steven-tey** [comment]
Planning to implement this very soon! Briliant idea Mahmoud! 🙏

**Comment by steven-tey** [comment]
Sneak peek 👀 

![CleanShot 2023-07-09 at 13 19 56@2x](https://github.com/steven-tey/dub/assets/28986134/99bb6c6f-c2ec-47bb-964e-a62e912d8d5a)

**Comment by steven-tey** [comment]
Shipped: https://dub.sh/changelog/monthly-summaries
