### ISSUE TITLE
[Bug] Archive links

### ISSUE THREAD

**Issue by fmerian** [steven-tey/dub#181]
seems like we can't archive links anymore? https://share.cleanshot.com/pZQLk7sZ

**Comment by steven-tey** [comment]
Ahh yes this is expected. This will be fixed when Tags feature are implemented #101

**Comment by fmerian** [comment]
awesome! keep up your great work, @steven-tey!

**Comment by fmerian** [comment]
@steven-tey IMHO there could be 2 more improvements here:
1. being able to press `Enter` to confirm the archive,
2. remember the action (e.g. don't show the popup again the next time you archive another link).

wdyt? should I re-open the issue or create a new one?
