### ISSUE TITLE
[Bug] Public link settings modal renders behind landing screen components

### ISSUE THREAD

**Issue by smonolo** [steven-tey/dub#184]
When editing a public link's configuration, the settings modal that displays is rendered behind some of the landing page components, making it partly unusable.

Evidence of the issue: https://cdn.smnl.it/ATuMNfifUM.gif

**Comment by steven-tey** [comment]
Hey @smonolo! Good catch – this [has been fixed](https://twitter.com/steventey/status/1652453078199574528)! It was due to an outdated version of `framer-motion` 😅
