### ISSUE TITLE
How are you doing the redirecting to a subdomain for certain routes

### ISSUE THREAD

**Issue by camerondrysdale** [steven-tey/dub#19]
Pretty new to Next.js and been looking through the source code but couldn't figure this one out.

How are you making certain routes such as `/login` redirect to use `app.domain.com/login`?

Thanks :)

Awesome job on the app btw! 👌

**Comment by steven-tey** [comment]
Good question – I'm basically adding it into my Dub.sh account:

![CleanShot 2022-09-23 at 09 02 15](https://user-images.githubusercontent.com/28986134/191978458-38db469c-3f3c-441a-8a64-0d5bff7d1163.png)

You can do the same by signing up at https://dub.sh/register and then going to https://app.dub.sh/links to start adding `dub.sh` domains :)

**Comment by camerondrysdale** [comment]
Sorry what I meant was more how is the subdomain added for the app directory... is this a Vercel thing?

**Comment by steven-tey** [comment]
oh, that's because I'm using middleware + I only defined the `/login` page in the `/app` directory: https://github.com/steven-tey/dub/tree/main/pages/app
