### ISSUE TITLE
Error while deploying to vercel :  { ReferenceError: prisma is not defined

### ISSUE THREAD

**Issue by zakimzf** [steven-tey/dub#193]
@steven-tey I am very sorry to bug you but i have ran into this problem while deploying dub to vercel ,been at it for about 2 hours straight but my efforts in vain! Please help me figure this error specifically with prisma ( i managed to get all the variables correctly!)
It says prisma is not defined. I even fixed the earlier import method which is now outdated with : import { Prisma }  from 'prisma/client';
still no success! Hope to hear back from you soon..thanks
![Screenshot 2023-05-05 191451](https://user-images.githubusercontent.com/67141555/236477431-ff292c94-f38f-4ac4-a738-4d2bf58d2fe9.png)

**Comment by timolarra** [comment]
same I am having the same problem, I wish someone can help

**Comment by amblerkr** [comment]
https://github.com/steven-tey/dub/discussions/147
I'd love to see a guide on how to host easily.

**Comment by steven-tey** [comment]
This should be fixed now since we replaced that route with https://github.com/steven-tey/dub/blob/main/app/%5Bdomain%5D/page.tsx! Sorry about the confusion before!
