### ISSUE TITLE
UTMs inside short links

### ISSUE THREAD

**Issue by steven-tey** [steven-tey/dub#214]
Courtesy of Matt:

> I'd like to have UTMs for the short link itself so I don't have to create different short links for the different placements in case they're redirecting to the same URLs. For instance, instead of creating https://dub.sh/github-homepage and https://dub.sh/github-email, I'd like to be able to distinguish traffic coming from https://dub.sh/github?utm_source=email and https://dub.sh/github?utm_source=homepage.

Also courtesy of @abass:

> Thing is, the ?ref= or ?utm_medium=, etc. gets removed with the redirect. Would be cool to be able to pass over some one-off UTM data, so the short link is more of a reusable short-link with variable UTM data (versus tying all the UTM data to the specific link—resulting in times with many of the same link being created with different UTM data).

**Comment by abass** [comment]
Amazing!!! Thank you so much—this is SO useful! 🤗🤗🤗
