### ISSUE TITLE
GPU usage jumps to 70% in the main page

### ISSUE THREAD

**Issue by zivtamary** [steven-tey/dub#215]
This is probably caused by the 3d globe component. might want to check this out! - using Edge browser.

**Comment by matytyma** [comment]
It is the globe and it's the same with [Vercel's website](https://vercel.com) :rofl:

**Comment by steven-tey** [comment]
Ahh yes this was one of the first issues on this repo: #11 😅 closing this as it's a duplicate

Might need to remove the globe entirely in the future <picture data-single-emoji=":sad-cowboy:" title=":sad-cowboy:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/sad-cowboy/b8413a8862df8f19.png" alt=":sad-cowboy:" align="absmiddle"></picture> 

You're on a windows laptop correct?

**Comment by matytyma** [comment]
This most likely happens only to laptops because their graphic cards are not the best (I'm on a Linux laptop btw)
