### ISSUE TITLE
Auto-copy public stats page link to clipboard

### ISSUE THREAD

**Issue by fmerian** [steven-tey/dub#218]
Similar to #149

Currently, the user flow to share a public stats page is:

1. Toggle the Public Stats Page on
2. Click on the icon to copy the link

Instead, we could simplify by auto-copying the link to the clipboard when toggle on.

**Comment by steven-tey** [comment]
Brilliant idea! Just implemented this! :)

https://github.com/steven-tey/dub/commit/ea5bd4caad77cf4934d65608e51af440b913e526
