### ISSUE TITLE
Feature Request: Link Inspection/Preview with `?` or `+`

### ISSUE THREAD

**Issue by dandanio** [steven-tey/dub#22]
So, there is no way to inspect a link. For example: https://dub.sh/jK5Bb6x, I would like to be able to do: https://dub.sh/?jK5Bb6x (or something similar) to inspect where it leads me. Let's end the rickrolling everybody!

**Comment by steven-tey** [comment]
Great idea! Will add this to the roadmap! :)

**Comment by dandanio** [comment]
Awesome! :) 

@steven-tey Suggestion: Maybe for UX (I spoke with my UX researcher friend), instead of prefix (!/?/+), do the suffix (for ease of typing - workflow being: copy - paste, arrow right, (sign !/?/+), [enter] - new page loads with wording like (https://dub.sh/jK5Bb6x redirects to https://www.cnn.com/, another link on the page for a link to VirusTotal (https://www.virustotal.com/gui/home/url)).

**Comment by Magicrafter13** [comment]
This would also be good as a safety measure against scams and other malicious links. (A link I found in the wild, which I believe to be malicious is actually how I discovered this project.)

**Comment by steven-tey** [comment]
Can't believe it took so long – but we finally shipped this! If you add `+` to the end of any `dub.sh` link, it should show something like this (with the option to report malicious links):

https://github.com/steven-tey/dub/assets/28986134/40270e96-0127-4930-958d-789b001b54c6
