### ISSUE TITLE
Shortlink name checking bug

### ISSUE THREAD

**Issue by matytyma** [steven-tey/dub#223]
## Problem
I've created a link and set **`/`** as the shortlink (I wanted to change the root domain redirect before I read the pricing). Everything was OK during the creation. Once created I discovered a lot of problems:
- Link still redirects to default Dub's webpage (rather my problem :smile:)
- Link statistics result with a 404
- Editing shows success but does not change anything
- Adding tag says 'Link not found'
- Archive shows empty warning notification
- Confirm delete loads as usually and then does nothing (does not even close)

## Possible Solution
Add a rule to check if the shortlink contains only slashes (I have tried making a PR, but my knowledge of TypeScript is absolutely zero :rofl:)

**Comment by steven-tey** [comment]
Whoops! That was one edge case that I didn't factor into 😅 I only checked if the [key contains "/"](https://github.com/steven-tey/dub/blob/main/pages/api/links/index.ts#L49-L51) and not if it's just "/" lol

Just [fixed this](https://github.com/steven-tey/dub/commit/2126342fdcefe403cbb7cd6b6a426636526b5c08) (also deleted your empty short link)! Thank you so much for catching & reporting this!

**Comment by matytyma** [comment]
Thanks for deleting my link, now you're going to do it once again.

You forgot about any amount of slashes, now I created a link with three of them. :sunglasses: This time, I've already created a PR.
- #224

**Comment by steven-tey** [comment]
@matytyma 😂 oh man, you're right! thank you for the PR, will merge it now! 🙏
