### ISSUE TITLE
support link is broken

### ISSUE THREAD

**Issue by zeke** [steven-tey/dub#229]
I just see a spinner here, and an error in the console about client.crisp.chat

![Screenshot 2023-06-02 at 4 32 10 PM](https://github.com/steven-tey/dub/assets/2289/d7106856-79c9-4b81-8cf2-c215bd690c69)

**Comment by zeke** [comment]
Womp that was it. 

Specifically, https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg

Closing!

**Comment by steven-tey** [comment]
ooof tricky! Thanks for surfacing this! 🙏
