### ISSUE TITLE
Account/Projects dropdown overflow behavior

### ISSUE THREAD

**Issue by redac** [steven-tey/dub#231]
Hi @steven-tey ! Have to say, wonderful execution on this app. 

I have a minor UI issue to point out. In the account/projects dropdown, overflow isn't proprely handled — the text overflows into selected account/project checkmark. 

<img width="588" alt="image" src="https://github.com/steven-tey/dub/assets/20306749/cc9d4c49-4291-48dc-a48f-8697882ae337">

I'll try and get a quick PR going to fix this. 

Thanks !

**Comment by steven-tey** [comment]
Good catch! Just fixed this – thank you!
