### ISSUE TITLE
Automaticly downloading RSS file on Changelog page

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [steven-tey/dub#236]
When on the changelog page the RSS file automatically downloads when scrolling down/hover over a changelog and when hovering over the download button after you already downloaded the file.

https://github.com/steven-tey/dub/assets/70828596/245c621b-8139-4319-8131-91cf54142a4a

**Comment by steven-tey** [comment]
Wow! This is super weird, what browser are you using?

I can't repro tho – anyone else can repro?

**Comment by Isaiah-Hamilton** [comment]
> Wow! This is super weird, what browser are you using?

Using FireFox 111.0.1 (64-bit) on macOS Ventura 13.2.1

**Comment by steven-tey** [comment]
@Isaiah-Hamilton Are you still facing this error?

**Comment by steven-tey** [comment]
Okay, sorry about that @Isaiah-Hamilton 🙏
