### ISSUE TITLE
Provide a link to the pricing page from the billing section.

### ISSUE THREAD

**Issue by fazlerocks** [steven-tey/dub#244]
After logging in, it can be challenging to locate the pricing page. To enhance UX and potentially increase conversions for dub.sh, consider adding a link to the pricing page within the billing section. This will make it convenient for users to compare the list of features.

**Comment by saulpw** [comment]
I agree, also ideally the pricing link would be in the same place on all pages (in the upper right near the account/signin link).

**Comment by steven-tey** [comment]
Update: Improved the onboarding → conversion flow as part of #238!

Also included a "[Compare plans](https://dub.sh/pricing)" button in the Upgrade modal as well 😄 

https://github.com/steven-tey/dub/assets/28986134/2a7c6c2b-b1bf-448b-9d4b-d8a9bb28a669

Thank you so much again for the feedback!
