### ISSUE TITLE
Billing section mentions 500K clicks per month for Enterprise customers

### ISSUE THREAD

**Issue by fazlerocks** [steven-tey/dub#245]
<img width="384" alt="image" src="https://github.com/steven-tey/dub/assets/6068418/386ed0f1-0a9a-41bf-8a98-6e2b53b90903">

On the pricing page, it states "unlimited clicks," but in the billing section, it mentions a limit of 500K links per month.

**Comment by steven-tey** [comment]
Good catch, thanks for surfacing! 

This will be fixed as part of #246 :)
