### ISSUE TITLE
app cannot be build

### ISSUE THREAD

**Issue by rashayagami** [steven-tey/dub#248]
When I tried building the app, I got an error saying ```the property onChatClose does not exist on the Crisp.chat``` object. 

<img width="818" alt="Screenshot 2023-07-03 at 10 58 00 AM" src="https://github.com/steven-tey/dub/assets/60523161/e977eb2c-4cca-496b-9151-55fd56f957c5">

**Comment by steven-tey** [comment]
Closing this for now– we've updated the self-hosting guide (re: #12) so feel free to try it again and let me know if it still doesn't work!
