### ISSUE TITLE
UX: Difficult to find upgrade button for paid plan

### ISSUE THREAD

**Issue by saulpw** [steven-tey/dub#250]
I had a hard time finding the upgrade button, I think the only place I could find is tucked away under the domain settings (*not* the account settings) and only on a popup from trying to set an option in the paid plan.  I was motivated though because I like the product, so I found a way :)

**Comment by steven-tey** [comment]
That's a great callout @saulpw – appreciate the feedback! I'm planning to improve the onboarding to upgrade flow very soon and will be addressing this then! :)

Also, thank you so much for upgrading to Pro! 🙏

**Comment by steven-tey** [comment]
Improved the onboarding → conversion flow as part of #238!

Also added an "Upgrade to Pro" CTA in the nav bar for free projects 😄 

https://github.com/steven-tey/dub/assets/28986134/2a7c6c2b-b1bf-448b-9d4b-d8a9bb28a669

Thank you so much again for the feedback!
