### ISSUE TITLE
Test on Vercel preview & Log in via Google providers on `dev` env

### ISSUE THREAD

**Issue by kevanantha** [steven-tey/dub#253]
I was wondering a couple things;

1. How to do you test the app on Vercel preview env since Vercel will generate the URL [(`<project-name>-<unique-hash>-<scope-slug>.vercel.app`)](https://vercel.com/docs/concepts/deployments/generated-urls)?

In my case (https://evestory-b2ft6wqrt-kevanantha.vercel.app/), it will be error if I click the "Log in" button (redirect to https://app.evestory-b2ft6wqrt-kevanantha.vercel.app/login)

2. Are you login via Google provider on `dev` env? If so, how do you do it? because I cannot find a way to login via Google provider on `dev` env. I see the source code like this:
 https://github.com/steven-tey/dub/blob/fbb9ac974e8585250b683a2c0750df68a1360e32/app/ui/home/nav.tsx#L62-L67
I already set the `NEXTAUTH_URL` to `app.localhost:3000`, but it will cause error `Access blocked: Authorization Error` because Google doesn't accept `http://app.localhost:3000/api/auth/callback/google` as Authorized redirect URIs

**Comment by steven-tey** [comment]
We basically use `preview.dub.co` as the preview URL and use [`vc alias`](https://vercel.com/docs/cli/alias) to alias the domain to the latest preview URL from Vercel. Will document this 🙏
