### ISSUE TITLE
Can't change the color of the QR-code

### ISSUE THREAD

**Issue by ashrafchowdury** [steven-tey/dub#257]
## Description

The **colour pallet component is currently not visible** because the parent component overlaps on it. This makes it difficult to see the colours that are being selected.

![Pricing - Dub and 4 more pages - Personal - Microsoft​ Edge 7_6_2023 2_03_38 AM](https://github.com/steven-tey/dub/assets/87828904/b0c593cf-8056-4ea6-8aa1-7c7dca619bac)

**Comment by steven-tey** [comment]
This should've been fixed! Thanks for reporting 🙏
