### ISSUE TITLE
Short Link URL on Mobile Gets Cut Off

### ISSUE THREAD

**Issue by abass** [steven-tey/dub#261]
Mobile keeps driving me a bit nuts because I'm skimming to see if a short link exists (efficient.tips/vs/harvest), but then realize I'm skimming the full link and not the short link, so no wonder I can't find it.

The actual short link gets cut off on mobile, which is IMHO the most important URL to be able to view. Even more important than skimming the long-link.

The copy/QR/stats icons take up such valuable horizontal screen real estate.

I've made this same mistake every single time I've gone to skim for a short link now on mobile (4th time now and keep forgetting each time). So definitely feels like a rough UX on mobile in terms of hierarchy.

![Screenshot_20230709-134728.png](https://github.com/steven-tey/dub/assets/5505994/f2cfdcbe-82bb-4a62-bf4a-545643a6eabf)

Wondering as well if the https:// could be scraped on the destination URL? Also not useful to visually see it in the list view. Subdomain is the first part of the destination URL that is useful to see.

**Comment by steven-tey** [comment]
Thanks a lot for the feedback here @abass! Gave you a shoutout in the Changelog post: https://dub.sh/changelog/improved-link-cards

**Comment by abass** [comment]
Looks SO good! Well done 👏👏👏
