### ISSUE TITLE
Using Vercel Postgres

### ISSUE THREAD

**Issue by taiqn** [steven-tey/dub#262]
Now Vercel has its own Postgres, it would be nice if you could instruct how to implement it

Thanks
Tai

**Comment by steven-tey** [comment]
Since Dub uses Prisma, you can just swap out the `DATABASE_URL` env var, change a few of the column formats in the Prisma schema, and it should work!

Closing this for now – hope this helps!

**Comment by Danm72** [comment]
Hey @steven-tey I'd probably keep this open and maybe make that part of a readme/onboarding I think its a preferred flow to keep a lot of the dependencies in Vercel rather than setting up other subs!

**Comment by steven-tey** [comment]
@Danm72 good point, converting it into a discussion instead!
