### ISSUE TITLE
Built without error but not works properly

### ISSUE THREAD

**Issue by taiqn** [steven-tey/dub#267]
Deployed to Vercel with Postgres and built without error, try to test by adding a valid link to shorten, nothing happens; don't know what's wrong?

Please take a look at https://dub-taiqn.vercel.app

**Comment by steven-tey** [comment]
Closing this for now because of lack of reproduction information! We've updated the self-hosting guide (re: #12) so feel free to try it again and let me know if it still doesn't work!
