### ISSUE TITLE
Dub.sh routing to pricing & changelog routes in localhost

### ISSUE THREAD

**Issue by ugniussilevicius** [steven-tey/dub#268]
# Issue: Unable to Understand Routing in `dub.sh` Project

## Description
Hi everyone,
This is my first time opening an issue, so please excuse any mistakes or potentially silly questions. I have been programming in JavaScript for around 5 months now and I'm currently trying to set up the `dub.sh` project for open source project exploration on my Mac.

I have successfully installed and connected to the database, and everything seems to be working fine. However, I'm having difficulties understanding the routing mechanism, particularly the routing that occurs when navigating through the home page navigation bar ("/") to other routes such as "/pricing" or "/changelog".

As far as I can tell, the main routing logic is implemented in the `middleware.ts` file, specifically in the following code snippet:

```javascript
if (domain === "dub.sh") {
  if (DEFAULT_REDIRECTS[key]) {
    return NextResponse.redirect(DEFAULT_REDIRECTS[key]);
  }
  if (await isReservedKey(key)) {
    return NextResponse.rewrite(new URL(`/dub.sh${path}`, req.url));
  }
}

```

Could someone please help me understand how this routing mechanism works? I'm particularly interested in understanding how the directories `[domain]` and `[dub.sh]` play a role in the routing process. Currently, when I click on "/pricing", it redirects me back to "/", and the same issue occurs with "/changelog" when running the project locally.

I would highly appreciate it if someone could take the time to provide a detailed explanation of this routing process. Not only would it help me, but I believe it would also be beneficial for other new developers who might encounter similar challenges.

Steven, thank you for creating this project! Your assistance in understanding this would be invaluable.

**Comment by elie222** [comment]
You're right about middleware.ts being the core place where the routing happens. If it isn't redirecting for you I assume it's a different configuration set up as the redirects do work on the dub.sh website.

A good way to work out what is happening when running locally is to add console logs into the flow and see where it stops and why.

This line obviously won't happen if domain isn't `dub.sh`.

```js
if (domain === "dub.sh") {
```

Let me know how you get on with that!

**Comment by steven-tey** [comment]
Oh, that's because I'm handling some of the routing logic with [Edge Config](https://vercel.com/docs/storage/edge-config) – `isReservedKey` [in this line here](https://github.com/steven-tey/dub/blob/main/middleware.ts#L54-L56) basically retrieves keys like `/blog`, `/pricing`, etc. and rewrites it to the `dub.sh` directory. 

You can hard code these values in locally to make this work! :)

**Comment by elie222** [comment]
> Oh, that's because we're handling some of the routing logic with [Edge Config](https://vercel.com/docs/storage/edge-config) – `isReservedKey` [in this line here](https://github.com/steven-tey/dub/blob/main/middleware.ts?rgh-link-date=2023-07-17T02%3A36%3A05Z#L54-L56) basically retrieves keys like `/blog`, `/pricing`, etc. and rewrites it to the `dub.sh` directory.
> 
> You can hard code these values in locally to make this work! :)

What's the reason you didn't hard code the reserved keys? Just an excuse to use Edge Config? :)

**Comment by steven-tey** [comment]
> What's the reason you didn't hard code the reserved keys? Just an excuse to use Edge Config? :)

Makes it easier to update it remotely (and instantly) without having to push a new deployment!

**Comment by ugniussilevicius** [comment]
I really appreciate your helpful responses to my question. Your assistance has given me a clear understanding of the project's technology and how it works. I've been exploring the infrastructure further and I'm truly impressed by the efforts of the Vercel team in making the web faster. Thank you both for your valuable help in my coding journey! 

Steven, your work on UI/UX of dub.sh project is fantastic :)
