### ISSUE TITLE
dub.sh throws Minified React errors

### ISSUE THREAD

**Issue by mdhruvil** [steven-tey/dub#272]
## Issue

When I visit [dub.sh](https://dub.sh), It throws multiple Minified React Errors,
When I change color of QR code client brakes and throws error. (ScreenShot Attached)

## Source
![image](https://github.com/steven-tey/dub/assets/132185979/6f95cbcc-48db-4e71-8bb9-bcf73787c545)
![image](https://github.com/steven-tey/dub/assets/132185979/4e4be887-2aa7-48c2-8dae-2abfa293a78b)

Tested In

- Brave
- Firefox

**Comment by steven-tey** [comment]
Thanks for reporting this! Aware of the React minified errors, but not sure how to repro the Application Error bug. I tried emulating it in Firefox via [Browserling](https://www.browserling.com/browse/win10/chrome114/https://dub.sh) but it didn't crash when I changed the QR code colors either – can you share more about that?

**Comment by mdhruvil** [comment]
@steven-tey  I also tried on Browserling it didn't crash on firefox  but it did crash on Chrome. I tried 3 times on chrome but it crashed only 1 time.
![image](https://github.com/steven-tey/dub/assets/132185979/3461d184-38ef-4938-8978-94440c0ad776)

**Comment by steven-tey** [comment]
@mdhruvil how did you get it to crash? Would love some steps to reproduce this so I can debug it 😄
