### ISSUE TITLE
[Feature] Project analytics dashboard

### ISSUE THREAD

**Issue by sebiweise** [steven-tey/dub#278]
Hey,
it would be great to have a analytics tab on project level to see all analytics data from the links that are connected to a project.

For example
![image](https://github.com/steven-tey/dub/assets/22999200/6f46d414-e74c-4763-a898-b7a1c6904a72)
![image](https://github.com/steven-tey/dub/assets/22999200/24317e64-4a9a-4fc9-9379-fd02a36b80af)

In addition it would be great to be able to apply some more filters.

**Comment by RokeJulianLockhart** [comment]
Maybe we could steal most of the code of the https://app.addy.io/ dashboard?

**Comment by steven-tey** [comment]
We recently just launched Project-level Analytics, which allows you to get a more granular sense of how your links are performing for a given time period (via a “Top Links” section). Here’s an example:

![CleanShot 2023-11-02 at 22 27 04](https://github.com/steven-tey/dub/assets/28986134/39e8e4ec-fec7-4679-a2fe-b030ba26b7e2)

Will be doing a proper launch for it tomorrow, but wanted to mention it here first :D
