### ISSUE TITLE
Which hard-coded values need to be changed to get an own instance running?

### ISSUE THREAD

**Issue by christianavi** [steven-tey/dub#281]
> Note: one-click deployment is a bit broken at the moment – you'll need to change some of the hard-coded values in the codebase to get it working. We're working on fixing this.

I'm curious which hard-coded values you referred to on this note.

**Comment by steven-tey** [comment]
Mainly instances of `dub.sh` – I've been trying to consolidate that in the constants here: https://github.com/steven-tey/dub/blob/main/lib/constants/index.ts#L41-L59

**Comment by timolarra** [comment]
We have been anticipating action on this matter for several months now, and yet, there has been no significant progress. It is becoming increasingly apparent that there seems to be a preference for us to utilize your proprietary services instead.

**Comment by steven-tey** [comment]
Apologies for the delay @timolarra – we are currently prioritizing several feature requests from paying customers such as SSO & REST API, after which we will work on improving the self-hosting flow.

Closing this issue for now to consolidate it with #12
