### ISSUE TITLE
How to fix invalid url question?

### ISSUE THREAD

**Issue by peteryang1756** [steven-tey/dub#284]
TypeError [ERR_INVALID_URL]: Invalid URL
10:07:07.772 | at new NodeError (node:internal/errors:399:5)
10:07:07.772 | at new URL (node:internal/url:560:13)
10:07:07.772 | at new Connection (file:///vercel/path0/node_modules/@planetscale/database/dist/index.js:48:25)
10:07:07.773 | at connect (file:///vercel/path0/node_modules/@planetscale/database/dist/index.js:144:12)
10:07:07.773 | at /vercel/path0/.next/server/chunks/6775.js:1676:103 {
10:07:07.773 | input: 'mysql -h aws.connect.psdb.cloud -u ---ssl-mode=VERIFY_IDENTITY --ssl-ca=/etc/ssl/cert.pem',
10:07:07.773 | code: 'ERR_INVALID_URL'
10:07:07.773 | }
10:07:07.775

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

**Comment by Wesleyvdk** [comment]
did you find a solution for this? I'm having the same error rn while on a previous project it still works fine with the same code
