### ISSUE TITLE
Top Clicks Today + This Week + Last 30 Days (In Addition To All Time)

### ISSUE THREAD

**Issue by abass** [steven-tey/dub#296]
It would be so cool to have something like Fathom has, e.g. top link clicks today/this week/this month/last month/this year/all time:
<img width="728" alt="CleanShot 2023-08-02 at 14 48 33" src="https://github.com/steven-tey/dub/assets/5505994/34333ada-78c3-4305-a221-3692b7e4a339">

Obviously that's way more robust, so more for example. And filtering should respect this, so I should be able to at a top level "this week" and then filter down by "X tag", so we can see the top performing/clicked tagged/filtered pages in that timeframe set.

**Comment by steven-tey** [comment]
We recently just launched Project-level Analytics (#439), which allows you to get a more granular sense of how your links are performing for a given time period (via a “Top Links” section). Here’s an example:

![CleanShot 2023-11-02 at 22 27 04](https://github.com/steven-tey/dub/assets/28986134/39e8e4ec-fec7-4679-a2fe-b030ba26b7e2)

Will be doing a proper launch for it tomorrow, but wanted to mention it here first :D
