### ISSUE TITLE
Allow For Link Notes/Details (Internal Only)

### ISSUE THREAD

**Issue by abass** [steven-tey/dub#297]
Would be nice to put notes in there somewhere:
![CleanShot 2023-08-02 at 15 58 48](https://github.com/steven-tey/dub/assets/5505994/cc2bd051-4070-4358-8546-2f1a9515f470)

e.g. Ramp pays $250 to each person for a qualified referral. That's just in my brain though. In Short.io I was storing that info in the title (in a kludgy way). I don't think it needs to present to the end-user. I'd also like to add in where the affiliate program is hosted (e.g. [PartnerStack](https://efficient.link/r/partnerstack))

**Comment by steven-tey** [comment]
Just shipped this: https://dub.sh/changelog/link-comments

Thanks for the feature request! 😁
