### ISSUE TITLE
Add Tag Should Be Alphabetical or Based On Popularity - Not Last Added

### ISSUE THREAD

**Issue by abass** [steven-tey/dub#299]
When adding a tag, I'm finding that the recommended tags are just the last added, which is rarely what I actually want:
<img width="300" alt="CleanShot 2023-08-02 at 16 04 16" src="https://github.com/steven-tey/dub/assets/5505994/62478650-127d-4a98-9774-cc65e3594675">

Ideally it sorted by popularity (like the sidebar shows), OR just simply alphabetical. Both would be more preferred over last added.

**Comment by steven-tey** [comment]
Thanks for reporting this – it should be fixed now (set to alphabetical)! 😄
