### ISSUE TITLE
Pass Password Unlock via URL Parameter

### ISSUE THREAD

**Issue by abass** [steven-tey/dub#300]
Could you pass a password via URL perameters? e.g. visiting a URL like:
https://efficient.app/apps/dub?pw=efficient

And assuming the password in this case was "efficient" it would actually enter the password and unlock it all in one fell swoop?

**Comment by steven-tey** [comment]
This works now in our latest update 😄 

https://dub.co/changelog/improved-password-links

https://github.com/steven-tey/dub/assets/28986134/716bd7e9-72b5-421d-a8e3-a1658b3aa0bc
