### ISSUE TITLE
AVG issue

### ISSUE THREAD

**Issue by soulveradio** [steven-tey/dub#305]
Hi, facing a problem with all our https://dub.sh/ shortlinks and all https://dub.sh/ links including your website not working as they are being blocked by AVG anti-virus since yesterday. The AVG anti-virus notice describes the issue as http://dub.sh links being a threat due to 'URL:Scam'. Can you please look into this issue?  
![dub-sh-avg-notice](https://github.com/steven-tey/dub/assets/141887701/d3ac506d-3fdf-4844-ab37-0462f430bdfe)

**Comment by Prashraj78** [comment]
might be your url is wrong

**Comment by soulveradio** [comment]
Update: AVG have removed the false positive and the issue is fixed.

**Comment by steven-tey** [comment]
Thanks for the headsup @soulveradio! Closing this issue for now!
