### ISSUE TITLE
Deleting existing invalid links doesn't work

### ISSUE THREAD

**Issue by Soft-Bred** [steven-tey/dub#31]
Trying to delete a link with unsupported characters doesn't work

link: `dub.sh/     ` (5 spaces)

https://user-images.githubusercontent.com/60551230/192106618-43cadba5-fe6d-41bb-8110-9a1c98718c31.mp4

**Comment by steven-tey** [comment]
oh yeah that's a bug – I can delete it manually for you on Monday (AFK this weekend) since that won't ever happen again in the future with proper link validation!

**Comment by steven-tey** [comment]
Went ahead and deleted all the links with unsupported characters for ya! Thanks again for the bug report! :)
