### ISSUE TITLE
Filtering Out Bot Views from Listview Count

### ISSUE THREAD

**Issue by abass** [steven-tey/dub#312]
Gosh, these bots are deceptive... Definitely want unique click tracking, but also, sorta wish I could exclude bots from total clicks as it's not helpful to see.
<img width="1231" alt="CleanShot 2023-08-13 at 12 12 10" src="https://github.com/steven-tey/dub/assets/5505994/60275842-4579-4fca-9007-e0b3760cf055">

e.g. which ones have most views from bots? Impossible to know without clicking in. So say 133 is the highest, but what if it was all bot clicks... Not useful :grimacing:
![CleanShot 2023-08-13 at 12 13 34](https://github.com/steven-tey/dub/assets/5505994/30426931-885b-4af7-9753-2427b5c50854)

**Comment by abhinaisai2002** [comment]
Hey, i would like to work on this

**Comment by steven-tey** [comment]
We just fixed this with the latest update: https://dub.co/changelog/bot-clicks-not-counted :)
