### ISSUE TITLE
Invited "members" to projects RBAC

### ISSUE THREAD

**Issue by jusso-dev** [steven-tey/dub#320]
More of a question, are there any plans to edit the amount of access invited members have in a created project? I wouldn't expect for example an invited member in my project to be able to remove me as a user and also be able to change the domain.

My specific use-case to provide context, I want to host my own dub and invite some non-for-profits I work with to create short links under a domain I own, I just don't want them to be able to priv-esc

**Comment by steven-tey** [comment]
Great idea! We've actually been quietly adding RBAC to secure certain features of the app – but this feature is only available on the Enterprise plan for now! Here's how it looks:

<img width="961" alt="CleanShot 2023-08-18 at 17 38 20@2x" src="https://github.com/steven-tey/dub/assets/28986134/53668da2-dcb0-4282-a814-b4758704019d">

<img width="1001" alt="CleanShot 2023-08-18 at 17 37 18@2x" src="https://github.com/steven-tey/dub/assets/28986134/4d06d1eb-c990-4f87-952a-35d513bde447">

**Comment by steven-tey** [comment]
Great idea! We've actually been quietly adding RBAC to secure certain features of the app – but this feature is only available on the Enterprise plan for now! Here's how it looks:

![CleanShot 2023-08-18 at 17 38 20@2x](https://github.com/steven-tey/dub/assets/28986134/80441df6-ed01-43b1-ae0a-1d9c25302fd2)

<img width="1001" alt="CleanShot 2023-08-18 at 17 37 18@2x" src="https://github.com/steven-tey/dub/assets/28986134/2e3b0ad9-3d88-46a2-b4cf-eefea09ce099">
