### ISSUE TITLE
Show the real count on hover 

### ISSUE THREAD

**Issue by fazlerocks** [steven-tey/dub#322]
<img width="129" alt="image" src="https://github.com/steven-tey/dub/assets/6068418/ac3e8d99-7a48-4dd0-a2ef-c6aef4dc3e12">

The numbers are rounded off in many places. It would be great to reveal the precise count when hovering over these areas.﻿

**Comment by steven-tey** [comment]
Great point! Just fixed this (as well as other parts of the app that have large numbers). Thank you!

<img width="457" alt="CleanShot 2023-08-18 at 19 39 31@2x" src="https://github.com/steven-tey/dub/assets/28986134/99b1f622-4718-4969-bf3f-cc0c88bc2b5f">

**Comment by fazlerocks** [comment]
Awesome! This looks great.
