### ISSUE TITLE
Redo self-hosting guide

### ISSUE THREAD

**Issue by meetblakey** [steven-tey/dub#325]
I've noticed requests for self-hosting have been pushed until various features have been enabled such as SSO, Bit.ly importer, etc.

Many if not all have now been implemented. It would be phenomenal if we could get a complete self-host guide end to end. All .env variables. How to set up Tiny bird. Etc. 

Right now, it's somewhat impossible to self-host and we'd love to embrace the open source nature of this!

Hope that's something that can be prioritized!

**Comment by TheOnlyWayUp** [comment]
Bump! I'd love this as well, how do we contribute?

**Comment by steven-tey** [comment]
Agreed, have been wanting to improve this for the longest time! Took a first stab at it today with this PR that publishes all the Tinybird pipes that Dub uses: https://github.com/steven-tey/dub/pull/331

**Comment by scesini** [comment]
Can be great a full guide to self-hosting.
Like many others, I really want to use it on my own server.
Or have the change to deploy on Vercel too.

**Comment by steven-tey** [comment]
Closing this in favor of #12: https://github.com/steven-tey/dub/issues/12#issuecomment-1758862381
