### ISSUE TITLE
Quickly add/edit tags

### ISSUE THREAD

**Issue by fmerian** [steven-tey/dub#326]
current flow to edit/add tags for existing Dub links:
1. select link
2. click `edit` (or press `E`)
3. Choose tag
4. Save changes

instead, I'd like to have another option in the popover to quickly add/edit tags.

![2023-08-23-O3tSxF8p@2x](https://github.com/steven-tey/dub/assets/1890087/284fd5e0-0ff5-487b-afa2-74685c7c40ef)

**Comment by steven-tey** [comment]
That's actually what we had before – a separate link tagging modal – but we merged it with the Link editing modal for better UX (re: https://github.com/steven-tey/dub/issues/240)

Closing this for now, but thank you! 🙏

**Comment by fmerian** [comment]
@steven-tey absolutely! what I suggested was:
1. add a quick link/keyboard shortcut in the popover that
2. open the Link editing modal with a focus on tags
