### ISSUE TITLE
Display the link creator's face below each link

### ISSUE THREAD

**Issue by fazlerocks** [steven-tey/dub#327]
<img width="810" alt="image" src="https://github.com/steven-tey/dub/assets/6068418/7dbf7cf8-fac4-43a7-b34d-468e5dfe2b01">

Hey, it would be really useful, especially in a team setting, if we could easily see who created a specific link. What do you think? :)

**Comment by steven-tey** [comment]
Agreed! Just added this:

<img width="381" alt="CleanShot 2023-08-23 at 21 51 19@2x" src="https://github.com/steven-tey/dub/assets/28986134/6ddceee1-3eae-4cd2-a8b4-c5ef31cae5cf">

<img width="423" alt="CleanShot 2023-08-23 at 21 51 24@2x" src="https://github.com/steven-tey/dub/assets/28986134/4468b7ee-3330-46cd-a931-f119ec36d91f">

Thank you for the feedback!
