### ISSUE TITLE
Design - spacing inconsistency in mobile

### ISSUE THREAD

**Issue by harel-tussi** [steven-tey/dub#33]
![Screen Shot 2022-09-25 at 11 53 17](https://user-images.githubusercontent.com/14964625/192135698-2ffbee94-bbf3-4774-a9ec-8025d9fe2ada.png)

I would be happy to fix that

**Comment by steven-tey** [comment]
Hey, sure! Feel free to PR! TBH mobile view is a bit wonky at certain parts (refer #9) so it definitely needs work! :)

**Comment by steven-tey** [comment]
Thank you again for the PR! :)

https://github.com/steven-tey/dub/pull/43
