### ISSUE TITLE
Getting an error when transfering domains or linking a domain

### ISSUE THREAD

**Issue by ziova** [steven-tey/dub#330]
Tested this out both with CNAME and A Name records and I get the following error:
![image](https://github.com/steven-tey/dub/assets/79858886/4d1e6e9b-31c0-4a5e-8a54-e200184f0e14)

Prior to this, I had been using Dub for a long time without any issues, I have retried with different subdomains and the root domain too but cannot get to the bottom of the issue

**Comment by steven-tey** [comment]
Hey! Can you send me the project slug (`app.dub.co/[slug]`)? I can look into it!

**Comment by steven-tey** [comment]
Closing for now, but feel free to send an email to support@dub.co if you're still facing issues!
