### ISSUE TITLE
Custom Social Media Card - Click to Upload - Visual Bug

### ISSUE THREAD

**Issue by ggoodwin** [steven-tey/dub#334]
When using **Chrome only**, I cannot reproduce in Edge or Firefox. I am experiencing a visual bug. It is not a blocker but makes things weird until link creation is finished or canceled.
I am starting an incognito session with no extensions loaded, performing a hard refresh, and clearing the cache.

I **Create a new link**. Click on the **Custom Social Media Cards** slider. Then hit **click to upload image**.
At this point, the two panels within the modal reduce in size significantly for some reason.

![Screenshot 2023-08-25 163242](https://github.com/steven-tey/dub/assets/1329130/6070711d-505c-4fe1-a40f-bda7d81e53be)

![Screenshot 2023-08-25 163450](https://github.com/steven-tey/dub/assets/1329130/dba64e67-9a5e-4682-a7a3-8a5482509106)

**Comment by mittalsam98** [comment]
Hey @ggoodwin I will try to fix this issue

**Comment by steven-tey** [comment]
This has been fixed thanks to @prathameshjchavan's PR #387!
