### ISSUE TITLE
Create password-protected links

### ISSUE THREAD

**Issue by harel-tussi** [steven-tey/dub#34]
It would be nice if there was an option to password-protect my link. 
As soon as the user clicks on the link, he is redirected to a page where he is asked to enter a password. 
Once he confirms the password, he is redirected to the original link.

**Comment by steven-tey** [comment]
Oooooh love this idea! It's definitely doable given the current setup – will try and knock this one out this week! 😄

**Comment by harel-tussi** [comment]
I would be happy to help.
Maybe develop the enter-password page?

**Comment by harel-tussi** [comment]
I would be happy to assist. Trying to create my first PR 😁

**Comment by rwlc** [comment]
Password protected links would need to be handled client-side, right?

**Comment by steven-tey** [comment]
No – we'll handle it with Middleware! Here's a simple example of how that would work: https://vercel.com/templates/next.js/basic-auth-password

In the case of Dub I'll probably add some custom UI to make the login page look pretty :)

**Comment by rwlc** [comment]
OH DAMN! I should have known about this. This is near I can't lie.

**Comment by steven-tey** [comment]
Password protected links is now live, thanks to #78 🥳 

https://user-images.githubusercontent.com/28986134/197374120-3b1d216b-631e-46d0-adf1-2ad487a0cca7.mp4

Feel free to try it out and let me know if there are any bugs 👀
