### ISSUE TITLE
Local Dev Setup Instructions

### ISSUE THREAD

**Issue by Autumn-Ou** [steven-tey/dub#346]
Currently no full instructions for getting a proper local dev environment running to do work for PRs beyond the "implementation" section of the readme

**Comment by steven-tey** [comment]
We added detailed instructions on how to set up env vars in [`.env.example` file](https://github.com/steven-tey/dub/blob/main/.env.example) recently!

Closing for now since it's a duplicate of #12, but planning to set up proper docs for this soon!
