### ISSUE TITLE
Deploy to Vercel Buid Error

### ISSUE THREAD

**Issue by sufaith** [steven-tey/dub#348]
<img width="1219" alt="image" src="https://github.com/steven-tey/dub/assets/10233977/4e6e2123-0d25-490a-a5b7-1d2e0172168c">

**Comment by steven-tey** [comment]
Good catch! These are not blocking errors but I reported this on the boxyhq/jackson repo nonetheless: https://github.com/boxyhq/jackson/issues/1535

Closing this for now but will be keeping an eye on that issue to resolve these errors!
