### ISSUE TITLE
Laggy website

### ISSUE THREAD

**Issue by CaedenPH** [steven-tey/dub#35]
The website `dub.sh` is extremely slow and sluggish, I can't scroll well at all and it gives a really unresponsive design. I have tested this on multiple devices and should probably get fixed, whether that means moving to a faster framework such as qwik or not

**Comment by harel-tussi** [comment]
This problem seems to be related to #11

**Comment by CaedenPH** [comment]
Yeah, thought so - couldn't find it

**Comment by steven-tey** [comment]
Hey @CaedenPH! I just pushed [this PR](https://github.com/steven-tey/dub/pull/39) that adds a fallback video for devices that don't have proper support for WebGL – let me know if this helps!
