### ISSUE TITLE
When will you fix the "Deploy to Vercel"

### ISSUE THREAD

**Issue by NekoZengL** [steven-tey/dub#355]
This problem has been around for a long time, and instead of fixing the bug, you guys keep selling the Pro Plan for app.dub.sh.

If you're short on money, the community can donate, but we need to deploy our own instance.

**Comment by steven-tey** [comment]
Hi! We recently improved Dub's self-hosting experience by:
- Adding detailed instructions on how to set up env vars in [`.env.example` file](https://github.com/steven-tey/dub/blob/main/.env.example)
- Added a [PR](https://github.com/steven-tey/dub/pull/331) that publishes all the Tinybird pipes that Dub uses

If you follow those instructions you should be able to set up Dub locally! We're planning to add a proper, well-documented self-hosting guide soon! Stay tuned! :)

P.S.: Closing this as it is a duplicate of #12

**Comment by NekoZengL** [comment]
> Hi! We recently improved Dub's self-hosting experience by:
> 
>     * Adding detailed instructions on how to set up env vars in [`.env.example` file](https://github.com/steven-tey/dub/blob/main/.env.example)
> 
>     * Added a [PR](https://github.com/steven-tey/dub/pull/331) that publishes all the Tinybird pipes that Dub uses
> 
> 
> If you follow those instructions you should be able to set up Dub locally! We're planning to add a proper, well-documented self-hosting guide soon! Stay tuned! :)
> 
> P.S.: Closing this as it is a duplicate of #12

thank you
