### ISSUE TITLE
Keyboard shortcut to confirm archive

### ISSUE THREAD

**Issue by fmerian** [steven-tey/dub#358]
currently, when I want to archive a Dub link: 
- I can press `A` to open the confirmation popup,
- then I must use the mouse to click the button.

instead, I'd like to use a keyboard shortcut to confirm the archive (pressing `Enter` opens the Edit page) :/

![Confirm archive](https://github.com/steven-tey/dub/assets/1890087/2a0229ca-4d73-418b-b3fc-4a4af9477fad)

**Comment by cosmiclasagnadev** [comment]
Hi @fmerian @steven-tey 👋 if no one's working on this, I would like to take it 🚀

**Comment by steven-tey** [comment]
This should be fixed now! sorry for the delay!

Uploading CleanShot 2023-10-11 at 20.43.30.mp4…

**Comment by fmerian** [comment]
that's great! thanks, @steven-tey!
