### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by bennetfabian** [steven-tey/dub#36]
It seems like this project has a custom stats solution.
Is it GDPR compliant by default and if not could it potentially be made compliant?

Also I would suggest adding information about GDPR compliance in the README and/or on [dub.sh](https://dub.sh).

**Comment by steven-tey** [comment]
Very good point! I ran out of time to set up proper docs on this (e.g. README section, `/privacy`, `/terms`) but AFAIK all the data that is collected on Dub are not personally-identifiable information (PII) so we should be good. All I need to do is document this – I've set a TODO to tackle this next week! :)

**Comment by steven-tey** [comment]
These have been added recently:
- https://dub.sh/privacy
- https://dub.sh/terms

Super simple stuff, will iterate and improve in the future!
