### ISSUE TITLE
Feature Request: 'Last Accessed Date' per link.

### ISSUE THREAD

**Issue by patrickmast** [steven-tey/dub#361]
Hello,

I've got a suggestion: How about adding a 'Last Accessed Date' for each link? This lets us know the last time someone clicked on a link. It should help us decide if a link is still useful or if we can clean it up.

I believe this could make our link lists cleaner and more efficient.

Thank you for considering this idea!

Best,
Patrick

**Comment by abhijeetnishal** [comment]
This suggestion looks good to me.
Hey @styfle I would like to work on this.

**Comment by styfle** [comment]
I think you tagged the wrong person. You probably want @steven-tey

**Comment by steven-tey** [comment]
Great idea! Just shipped this: https://dub.co/changelog/sort-last-clicked

Thanks for the feature request!
