### ISSUE TITLE
[BUG] Account Deletion Redirect Not Working

### ISSUE THREAD

**Issue by Saurav-Pant** [steven-tey/dub#364]
In the codebase, 

It is clearly stated that after a user deletes their account, they should be redirected to the /register route. However, the current implementation does not seem to be functioning as expected. 

To provide clarity and help resolve this issue, I have added relevant code snippets and a video demonstration

![code](https://github.com/steven-tey/dub/assets/103263909/39cfcaa8-2389-4cca-a443-db7afb01d856).

https://github.com/steven-tey/dub/assets/103263909/f25cb2dc-1e53-4e88-a150-435d347e7a34

If you believe that this issue requires attention and action, please assign it to me so that I can investigate and work on a solution.

**Comment by gabefletch** [comment]
This seems to have been resolved as I was not able to repro the behavior you described. I was taken to /register upon account deletion (throwaway account).

**Comment by steven-tey** [comment]
Glad to hear that @gabefletch! Closing this issue for now <picture data-single-emoji=":ty-heart:" title=":ty-heart:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/ty-heart/fcc570066d2722f0.png" alt=":ty-heart:" align="absmiddle"></picture>
