### ISSUE TITLE
Undo 'Archive'

### ISSUE THREAD

**Issue by fmerian** [steven-tey/dub#365]
as a user, if I archive a link by mistake, I'd like to recover it quickly.

currently, the only option is to: 
1. show archived links then
2. unarchive link

instead, I'd like to be able to undo it.

![Undo?](https://github.com/steven-tey/dub/assets/1890087/0a5c6747-b783-41f6-97c0-d5cb5169b7e9)

**Comment by RockingThor** [comment]
Can I get this issue assigned to me?

**Comment by xonx4l** [comment]
Is this looks good to you @fmerian .

**Comment by steven-tey** [comment]
left a comment @xonx4l 

assigned the issue to you too @RockingThor

**Comment by unrenamed** [comment]
Hi @steven-tey , do you require assistance with this matter? Based on my analysis, it appears that the solution is relatively straightforward in this specific case. Let me know if I'm missing anything:

1. [Sonner's ](https://sonner.emilkowal.ski/) toast API  supports an action callback with a customizable text for the button, such as "Undo." We can use it to send the **undo** request to the API (with the opposite boolean flag in its body) whenever a user clicks the button.
2. The logic for archiving links seems unsophisticated: a boolean flag is simply modified in the database. Consequently, we can submit numerous requests to undo, redo the action, and so forth. This approach is applicable for both "Archive" and "Unarchive" state changes. Thus, it seems that only some adjustments on the UI side are necessary.

So the idea is as follows:
```ts
toast.success(`Successfully ${archive ? "archived" : "unarchived"} link`, {
    action: { label: "Undo", onClick: undoAction }
});
```

Now, the undo action can also run a "promisified" toast with the loading text for better UX:
```ts
toast.promise(sendArchiveRequest(link, !archive), {
    loading: "Undo in progress...",
    success: () => "Undo successful! Changes reverted."
});
```

However, if the aim is to make this feature adaptable to cover more app actions, the aforementioned considerations might not suffice. For instance, reversing the "Delete" action would necessitate modifications to both the database and API.

Nevertheless, if you find the solution I suggested sufficient for address this concrete "undo (un)archive" problem, I would be delighted to collaborate on implementing the feature and submitting a pull request.

**Comment by steven-tey** [comment]
@unrenamed that's a fantastic analysis! The UX you suggested above sounds perfect (brilliant idea to leverage Sonner's undo API) – only suggestion that I have is maybe we can add an CMD+Z listener as well during this allow-undo period (unless the Sonner API supports this as well)

Longer term, we'd ideally want to be able to undo other actions as well (delete link, edit link, etc.) but that would require a bit more thought since it's more than just toggling a boolean field in the database 😅

**Comment by unrenamed** [comment]
@steven-tey  👋, the PR is all set for a code review. Thanks for suggesting the CMD + Z trigger – it's now implemented and ready for your feedback.

Quick question for both @steven-tey and @fmerian : What would be an ideal duration for the allow-undo period? Currently, it's set to 5 seconds, mirroring the default duration for the undo email feature in Gmail. Do you think it's good as is, or should we consider extending it to 10 seconds or perhaps something in between?

Appreciate your input!

**Comment by fmerian** [comment]
> What would be an ideal duration for the allow-undo period? Currently, it's set to 5 seconds, mirroring the default duration for the undo email feature in Gmail.

sounds perfect. thanks, @unrenamed. keep up your great work!
