### ISSUE TITLE
Filter Links component  are completely overlflowing 

### ISSUE THREAD

**Issue by Cvr421** [steven-tey/dub#370]
Filter Links component  are completely overlflowing 
screen short 
![Dub - Link Management for Modern Marketing Teams - Google Chrome 05-09-2023 21_37_54](https://github.com/steven-tey/dub/assets/82499697/46fdb7ac-d5f4-429f-8b27-0fb60fb5706d)

Hii @steven-tey if you feel this issue is relevent then Let me know and Assign it to me. so i can start working on it  .

**Comment by steven-tey** [comment]
Thanks for reporting! It was a one-line fix so I just went ahead and fixed it, but appreciate the headsup!
