### ISSUE TITLE
Potential issue with billing cycle days in 31 days

### ISSUE THREAD

**Issue by TotomInc** [steven-tey/dub#374]
Hey, if I've properly read the source-code, it looks like there is an issue with billing cycles.

1. When someone subscribes to a plan, the current day of month is stored inside `billingCycleStart`:

https://github.com/steven-tey/dub/blob/11108485a2853ddb7f2086023079ae93f53f10ce/pages/api/stripe/webhook.ts#L71-L79

2. On the CRON util that is called everyday, you check for projects that have the `billingCycleStart` for today:

https://github.com/steven-tey/dub/blob/11108485a2853ddb7f2086023079ae93f53f10ce/app/api/cron/usage/utils.ts#L42-L50

What happens if I'm subscribing the 31 of a month? The next month is in 30 days, my quota will not be reset?

The same should apply for months in 28 days like February.

E.g. if current month has 28 days, apply billing cycles to projects that have `billingCycleStart` between `28` and `31`.

**Comment by steven-tey** [comment]
Oh dang, fantastic catch! Pushing up a fix for it right now – thank you so much!
