### ISSUE TITLE
Invalid URL Error When Trying to Add Specific URL

### ISSUE THREAD

**Issue by xabru** [steven-tey/dub#375]
**Problem Description**
I attempted to add the following URL as a link in [dub.sh](https://dub.sh/), a URL shortening service:

URL: https://raw.githubusercontent.com/oven-sh/bun/main/Dockerfile

However, I received an error message indicating that the URL is invalid.

**Steps to Reproduce**
Access [dub.sh](https://dub.sh/).
Try to shorten the URL https://raw.githubusercontent.com/oven-sh/bun/main/Dockerfile.
**Expected Behavior**
I expected to be able to shorten the mentioned URL without receiving an "invalid URL" error.

**Additional Information**
The URL in question is valid and accessible. Is there any specific restriction or special consideration when adding URLs in [dub.sh](https://dub.sh/)? I would appreciate any guidance or a solution to this issue.

Thank you!

**Comment by steven-tey** [comment]
@xabru sorry about this – it was a bug in our regex implementation for detecting phishing/malicious links that caused this to fail – it's since been fixed!

**Comment by temrb** [comment]
May be related-- I get invalid url issue for .ai urls

i.e. https://beacons.ai/
