### ISSUE TITLE
This Edge Function has crashed.

### ISSUE THREAD

**Issue by jugaaadd** [steven-tey/dub#377]
![image](https://github.com/steven-tey/dub/assets/109716460/93b220e4-d0a5-415b-a036-e73755a45f3c)

This error is being shown after every click in my links. Please fix the issues as fast as possible!!

**Comment by devbytemehedi** [comment]
I am also having same problem

![librewolf_7T7j7PuDk2](https://github.com/steven-tey/dub/assets/89072438/34cfa4c1-dc87-4fa1-a596-8ff4bfdf1135)

**Comment by JammUtkarsh** [comment]
Same: https://links.utkarshchourasia.in/resume

**Comment by aidrecabrera** [comment]
Same problem here.

![image](https://github.com/steven-tey/dub/assets/61798731/c5e5481e-1b28-4555-ae71-5fe903529c99)

**Comment by steven-tey** [comment]
Hey everyone! This should be fixed now – huge apologies for the downtime!
