### ISSUE TITLE
OIDC/SAML support

### ISSUE THREAD

**Issue by lohrm-stabl** [steven-tey/dub#38]
Can we use OIDC or SAML to connect our company's IAM directory to dub?

**Comment by steven-tey** [comment]
Not currently, no, but I'm planning to add SSO/SAML support in the next couple of weeks! What kind of data are we talking about here? Feel free to email me steven@dub.sh! :)

**Comment by deepakprabhakara** [comment]
@steven-tey We have an npm module for SAML SSO if you want to avoid rolling out your own implementation - https://www.npmjs.com/package/@boxyhq/saml-jackson. Great project, congrats!

**Comment by steven-tey** [comment]
@deepakprabhakara – I'm actually already looking to integrate Boxy (hat-tip to @peerrich for the recommendation)! 😄 

Thanks for sending that over!!

**Comment by DrMxrcy** [comment]
+1 On this. Hope we can do this on the Self Deployed option!

**Comment by mwllgr** [comment]
+1 from me too. OIDC/SAML support would be great.

**Comment by RayhanYulanda** [comment]
+1 from me too

**Comment by steven-tey** [comment]
I got severely delayed on this, but this is still at the top of my TODO list (even higher priority than #73 API support actually).

There is one blocking feature that I'm currently working on (moving billing to project level) before I can start working on this, but I'm planning to ship this by April <picture data-single-emoji=":fingers-crossed-bart:" title=":fingers-crossed-bart:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..ljw6DosIzW5h3IS8.F9VpYh7nICaphWTg38yGS3UrW9PC5nKweWDVULHSbp4eomuHLDCRMgIWR9GIH7hEVJvqeaVXU_gB_Fv5-vxSx2DV6DVPet8evt-LtbXy0Ioc7DZvJHpQlP0ajNGtyVWxBXdb25CD.INoMmuGS9y9qk1xi3USUjQ" alt=":fingers-crossed-bart:" align="absmiddle"></picture> 

Will keep y'all posted!

**Comment by steven-tey** [comment]
Update here – we just launched Google OAuth: https://dub.sh/changelog/sign-in-with-google

Also added a waitlist sign up form for folks interested in SSO/SAML – feel free to sign up for that if you're interested in that:

![CleanShot 2023-05-28 at 12 07 55](https://github.com/steven-tey/dub/assets/28986134/4a55c1e0-bc9f-4eef-b52b-897d33ed62af)

**Comment by steven-tey** [comment]
Sneak peek 👀 

https://github.com/steven-tey/dub/assets/28986134/a7071c9e-efd7-4c53-8ff0-f7874106ab22
