### ISSUE TITLE
Text background mismatch on /abuse page

### ISSUE THREAD

**Issue by fjsnow** [steven-tey/dub#383]
Don't believe this is intentional, but on the abuse page on the text "If you’ve encountered a harmful Dub link, please use this form to report it. We take these reports very seriously and will review and take appropriate action." there is an background colour applied to the text that's similar (but not the same) as the background.

<img width="684" alt="image" src="https://github.com/steven-tey/dub/assets/105566242/c87f2068-d181-4d11-9bde-f2f48786bf9a">

The text is from the tally.so integration, so most likely would have to be changed there

**Comment by gabefletch** [comment]
Along with the text background being brighter than the rest of the page, the text itself from the `tally.so` integration is also slightly lighter in color than the rest of the text on the /abuse page. This most likely isn't very high priority but is noticeable if you look hard enough.

**Comment by ShubhamVsCode** [comment]
Can i work on this issue?

**Comment by Yash-Ainapure** [comment]
what color do you want then? black?
as a beginner i would like to contribute here

**Comment by steven-tey** [comment]
This should be fixed now. Sorry about that!
