### ISSUE TITLE
Password-protected links w/ device targeting enabled redirects to the original destination URL

### ISSUE THREAD

**Issue by unrenamed** [steven-tey/dub#385]
I was testing the link creation and noticed that if iOS or Android targeting is enabled **and** the link is protected with a password, the iOS / Android users will be redirected to the **original destination URL** on opening.

**Steps to reproduce:**
1. Open the link creation modal
2. Enter any **Destination URL** (e.g. https://www.google.com) and **Short link**
3. Toggle password protection on and enter your password
4. Toggle iOS/Android targeting on and enter a different redirection link
5. Save changes
6. Open the link on your iOS/Android device and in your web browser on your PC/laptop

**Actual behavior:** 
Both links redirect to the **Destination URL** (https://www.google.com in this example).

**Expected outcome:**
Links opened on iOS/Android redirect to URLs provided in Step 4.

_I haven't found any explanation for such behavior in [Dub Help Center ](https://dub.co/help). Yet I'm not quite sure this is a bug. Does anyone have an idea whether this is a bug or the actual behavior is already expected?_

**Dev note**
This makes sense given the code to rewrite the URL to `/protected/[domain]/[key]` [lib/middleware/link.ts](https://github.com/steven-tey/dub/blob/b4c3dc44d0632218d361197fe95851d3e3207f4a/lib/middleware/link.ts#L82) is executed earlier than the middleware starts checking the user agent data containing device details. However, this finding doesn't answer my question above.

**Comment by steven-tey** [comment]
Ah good catch – this is expected behavior since device targeting is not supported currently for password protected pages. Curious what would your use case be?

Will document this in the meantime!

**Comment by unrenamed** [comment]
@steven-tey Thank you for verifying this is the expected behavior. Yes, it'd be great if this limitation is documented so users don't get confused when combining several options for their links.

As for an example use case, I don't have any at the moment. As I said, I've been just testing the app and was curious about it from the dev perspective 👨‍🔬

Although I can imagine a case when protected links are necessary (e.g. URL params contain some sensitive info), I don't think such a scenario should support device targeting unless there is a high demand for it.

**Comment by steven-tey** [comment]
Just documented this: https://dub.co/help/article/how-to-create-link

![CleanShot 2023-09-23 at 20 30 07](https://github.com/steven-tey/dub/assets/28986134/5cefed55-a070-461a-bd30-87d3288fe8b8)
![CleanShot 2023-09-23 at 20 30 07](https://github.com/steven-tey/dub/assets/28986134/58eb1a4b-ff45-4c7e-b026-f12cbf7b6404)

Thank you so much again for the heads-up!

**Comment by steven-tey** [comment]
@unrenamed  Good news – this limitation has been fixed in our latest update: https://dub.co/changelog/improved-password-links

You can now use password protection with geo/device targeting! :)
