### ISSUE TITLE
dub.sh Links Only Connect via Chrome

### ISSUE THREAD

**Issue by gabefletch** [steven-tey/dub#389]
As the title says, any dub.sh link I try to utilize will only resolve and redirect if using Chrome. Using Firefox, Safari, or trying to open the link via another app won't work at all and throws one of the three following errors:
"Unable to connect"
"Failed to load"
or "The server at dub.sh is unresponsive"

I've tried multiple different networks, browsers, and every logical solution but links still will only work properly when using Chrome on desktop. Even the normal "dub.sh" link with no slug doesn't work. Dub.co seems to load on all browsers just fine as expected.

**Comment by steven-tey** [comment]
That could potentially be due to your local ISP blocking `dub.sh` links: https://dub.sh/blacklist

Can you try switching to a different network (e.g. mobile network) and see if the issue persists?

**Comment by gabefletch** [comment]
The issue still persists on a mobile network. I know that my ISP is not blocking `dub.sh` links because they still connect properly when using Chrome, but no other browser.

**Comment by steven-tey** [comment]
<picture data-single-emoji=":mind-blown-telegram:" title=":mind-blown-telegram:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/mind-blown-telegram/8da1ff249e3eff45.gif" alt=":mind-blown-telegram:" align="absmiddle"></picture> this is super interesting – I can't seem to repro on Safari, Microsoft Edge, or Firefox – literally just downloaded Firefox to test this out 😅 

Is there a specific link that doesn't work? E.g. does the default https://dub.sh/github link work for you?

**Comment by gabefletch** [comment]
As far as I can tell not a single dub.sh link works unless I'm on Chrome. I've tried https://dub.sh/github as well as links I've made myself (which is how I discovered this). 

I just now downloaded Chrome for iOS to see if the issue persists there as well. It does, both on WiFi and cellular. So it seems that for some reason I'm only able to use dub.sh links on Chrome for desktop.

I've also tried using some of my links from within apps (e.g. Instagram bios, etc.) with the same result.

**Comment by steven-tey** [comment]
😕 that's really weird – I just tested https://dub.sh/gabe in all 4 browsers (Chrome, Edge, Firefox, Safari) and it works without a hiccup for me.

What happens when you `curl` / `httpstat` a `dub.sh` link in your terminal? Do you get a 307 redirect?

**Comment by gabefletch** [comment]
<img width="612" alt="Screenshot 2023-09-23 at 11 52 59 PM" src="https://github.com/steven-tey/dub/assets/38300939/fa8fe6f2-8a2c-4e73-9f47-ad8e0e959193">

**Comment by steven-tey** [comment]
Are you using a VPN by any chance?

**Comment by gabefletch** [comment]
I'm not.

**Comment by gabefletch** [comment]
After testing across three devices it looks like I can now connect without an issue. I didn't change anything with my network settings so I'm not exactly sure what was causing it.

**Comment by gabefletch** [comment]
Both Terminal and PowerShell present a redirect as expected as well.
