### ISSUE TITLE
Feature Request: Support custom brand logo on QR code

### ISSUE THREAD

**Issue by snpranav** [steven-tey/dub#393]
Instead of the dub.co logo that gets put on QR codes generated for links, it would be nice if the logo could be customized with a brand logo for all links within a domain.

**Comment by meta-gravity** [comment]
I would love really this too @steven-tey ☺

**Comment by steven-tey** [comment]
Hey @snpranav @meta-gravity! Custom QR codes is a Pro feature on Dub: https://dub.co/help/article/custom-qr-codes

Feel free to set it up by referring to that guide and let me know if you run into any issues! :)
