### ISSUE TITLE
No obvious method for account recovery or password reset

### ISSUE THREAD

**Issue by gabefletch** [steven-tey/dub#395]
### Discussed in https://github.com/steven-tey/dub/discussions/254

<div type='discussions-op-text'>

<sup>Originally posted by **ACXCloud** July  5, 2023</sup>
https://dub.sh/gclone

this is my shortened link I forgot what email I used to signup can you help me out ?</div>
There doesn't appear to be an obvious method of account recovery for email-based accounts that could resolve the issue described in the discussion above. Based on `app.dub.co/login` the only option for this user would be to create an entirely new account.<br>
I realize that this is a pretty old discussion but it seems important as other users could very well have the same difficulty with account recovery in the future.<br>
<img width="325" alt="Screenshot 2023-09-27 at 5 39 34 PM" src="https://github.com/steven-tey/dub/assets/38300939/94b5e9de-b65b-4186-8a12-4b016238c1f0">

**Comment by ACXCloud** [comment]
He bro what to do let me know my email i forgot which one i used it was log ago now i need to update the content of it.
I had a custom domain at that time which expired and is expensive af might be i have used that email to signup.

as I tried all my current emails none seems to have the link in the dashboard.

any help would be appreciated.

**Comment by steven-tey** [comment]
Sorry for the late response here – @ACXCloud if you can send us an email at support@dub.co, I can get you the email you used for that link!

**Comment by steven-tey** [comment]
@gabefletch that's a very good point – I believe that's an issue a lot of passwordless login platforms face as well. For privacy purposes we won't be able to create something like https://dub.co/tools/inspector, but if folks email support@dub.co we're happy to help with account recovery! :)
