### ISSUE TITLE
[Feature Request] Analytics grouped by project

### ISSUE THREAD

**Issue by DawgZter** [steven-tey/dub#397]
Would be great to see analytics for my entire project. In practice, could be cumulative stats of all links for a project.
Ideally would like to see this feature expand to support storing links in folders and then seeing cumulative analytics for links within a folder.

**Comment by steven-tey** [comment]
Great idea! Related to #278 and #279 – will add this to the roadmap!

**Comment by steven-tey** [comment]
closing in favor of #278
