### ISSUE TITLE
[Bug]: search does not return expected destinations / results

### ISSUE THREAD

**Issue by natterstefan** [steven-tey/dub#404]
Hi @steven-tey,

I shared this issue with you via E-Mail, but this could also be of interest as an issue in the official repo. Here is an example I'm talking about:

I've looked up the following string `http://localhost:3010/hotel/011428dc-45c2` (the string I am interested in is even longer with query params), and I get results like this:

<img width="1164" alt="image" src="https://github.com/steven-tey/dub/assets/1043668/9277dc65-c951-4f18-9fc6-3712b33a23bb">

The app's request looks like this: `https://app.dub.co/api/links?search=http%3A%2F%2Flocalhost%3A3010%2Fhotel%2F011428dc-45c2&showArchived=true&slug=xxx`

This makes e.g. validating if destinations already exist (with the API) before creating new links impossible.

## Related Code

https://github.com/steven-tey/dub/blob/a2a4f43eb5f606eb159a59e882418aefdbee9264/lib/api/links.ts#L30-L61

Edit: Well, what a coincidence, this is Issue #404! 😅 🤣

**Comment by steven-tey** [comment]
This is interesting, probably something to do with MySQL handles search – will look into it! 🙏 

Also love the #404 coincidence 😄

**Comment by patrickmast** [comment]
Was about to report same issue 🤩
I also wanted a way to know if a shortlink is already created before creating a new one.

Thanks!

**Comment by natterstefan** [comment]
Hi @patrickmast,

thanks for the feedback. This is something I requested as a new feature as well. Please consider adding a vote to the open discussion: <https://github.com/steven-tey/dub/discussions/408>.

**Comment by patrickmast** [comment]
Any news on this? Thanks!

**Comment by steven-tey** [comment]
This has been fixed! <picture data-single-emoji=":cele-cry:" title=":cele-cry:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/cele-cry/0b3863f465db725f.png" alt=":cele-cry:" align="absmiddle"></picture> 

Please let me know if you are still facing any issues @natterstefan @patrickmast
