### ISSUE TITLE
[Free plan] Clarify that users won't be able to add, edit, or delete links lifetime when usage exceeds limit

### ISSUE THREAD

**Issue by admehta01** [steven-tey/dub#405]
https://github.com/steven-tey/dub/blob/main/app/ui/home/pricing.tsx#L264

Current: `If you exceed your monthly usage, your existing links will still work, but you need to upgrade to view their stats/add more links.`

Proposed: `If you exceed your monthly usage, you will not be able to add, edit, or delete links anymore. Your existing links will still work.`

Would also propose this is stated on the page, not behind a tooltip.

**Comment by admehta01** [comment]
The message here is much clearer 👍🏻. Maybe can reuse this language a bit?

![image](https://github.com/steven-tey/dub/assets/1946614/5ef2940c-a47a-4761-a4e7-a806605b0856)

**Comment by steven-tey** [comment]
Great idea, will fix – this is also in the Pricing FAQs section:

![CleanShot 2023-10-05 at 22 41 07](https://github.com/steven-tey/dub/assets/28986134/487676e5-1325-450c-880b-c1b4295ae728)
