### ISSUE TITLE
Redirection for the root domain

### ISSUE THREAD

**Issue by surjithctly** [steven-tey/dub#41]
Hey Steven,

I'm switching from another provider and it seems I cannot give a redirect to the root domain I added. Currently it redirects to dub page. I wanted to redirect to another website. Is it possible?

I tried with blank & / but didn't work.

**Comment by steven-tey** [comment]
Hey @surjithctly! Thanks for the question! And yup – folks have asked about this before, I'll be implementing it ASAP 💪

**Comment by steven-tey** [comment]
👀 https://github.com/steven-tey/dub/pull/46

**Comment by steven-tey** [comment]
It's merged! 🥳

**Comment by surjithctly** [comment]
That was fast. Thank you.
