### ISSUE TITLE
Invalid url (.ai domains)

### ISSUE THREAD

**Issue by temrb** [steven-tey/dub#410]
When trying to shorten some .ai domains gives invalid URL

i.e.
https://beacons.ai/*

<img width="421" alt="Screenshot 2023-10-08 at 4 48 56 PM" src="https://github.com/steven-tey/dub/assets/22056864/d6118216-fd61-42ca-816f-1cd29900c859">

though other ai domains like https://easy-peasy.ai/ -- it shortens without error

Related: #375

**Comment by steven-tey** [comment]
This was actually due to abuse cases using the `beacons.ai` domain – just went ahead and unblocked it so it should work now!
