### ISSUE TITLE
When Switching between Home page to Changelog page Users get automatically logged out

### ISSUE THREAD

**Issue by AbhishekCS3459** [steven-tey/dub#436]
Steps to Reproduce:
Step 1)  Do Signup with google in this page: https://dub.co/
Step 2) Switch over to this page: https://dub.co/changelog
Expected : User should not be logged out.
Current Behavior User logged out and needs to login again. 

After Signing in Homepage:
![image](https://github.com/steven-tey/dub/assets/94506000/39c51233-df3e-40bf-8c39-3232d816efc5)

Changelog Page:
![image](https://github.com/steven-tey/dub/assets/94506000/798d3d23-c483-41a8-963b-d6f9de022ac7)

**Comment by AbhishekCS3459** [comment]
@styfle  I am interested to fix this issue kindly assign it to me.

**Comment by steven-tey** [comment]
This should be fixed now, sorry about that!
