### ISSUE TITLE
Issues with short linking twitter profiles/tweets

### ISSUE THREAD

**Issue by arty4999** [steven-tey/dub#45]
Good day to you all here,

There seems to be an issue when linking to twitter, it produces a "**Too Many Redirects**" error when using the non-self-hosted version of Dub.

My "setup" is using a custom domain which uses Cloudflare for DNS/protection

Thing's I've tried:

- Disable caching in Cloudflare - didn't work
- Disabling Cloudflare completely - didn't work
- Change domains in Dub - didn't work
- Check if twitter can even be short linked using another service(bit.ly) - it works there

**Comment by steven-tey** [comment]
Hey @arty4999! Thanks for the bug report! To confirm – you're referring to the hosted version of Dub right (https://app.dub.sh)?

If so, which domain are you trying to add? Feel free to send me an email at steven@dub.sh if you prefer to let me know in private! :)

**Comment by arty4999** [comment]
hello @steven-tey,

I'm indeed referring to the hosted version of Dub. The domain added is "breadcat.cf"

Although, it has started working now for some reason, I've not changed anything at all on DNS or website sides, but it works now. This could be a one-off issue.
