### ISSUE TITLE
Reserved Keys not working

### ISSUE THREAD

**Issue by alerimoficial** [steven-tey/dub#450]
Hi,

You might need to fix the function isReservedKey at edge-config.ts to add .includes(key) to return a boolean.

 if (!process.env.EDGE_CONFIG) {
    // If EDGE_CONFIG is not set, these are the default reserved keys
    return [
      'blog',
      'help',
      'pricing',
      'changelog',
      'metatags',
      'terms',
      'privacy',
    ]**.includes(key)**
  }

**Comment by steven-tey** [comment]
Great catch, just fixed this, thank you!
