### ISSUE TITLE
Why AGPL?

### ISSUE THREAD

**Issue by fakerybakery** [steven-tey/dub#459]
Hi,
Thanks for making this great project!
I'm writing a [blog post](https://blog.mrfake.name/2023/11/01/open-source-projects-are-switching-to-agpl/) and am curious about your decision to switch to AGPL.
Thank you!

**Comment by steven-tey** [comment]
That's a great article! Wrote about our reasoning in the README under "License":

> Inspired by [Plausible](https://plausible.io/), Dub is open-source under the GNU Affero General Public License Version 3 (AGPLv3) or any later version. You can [find it here](https://github.com/steven-tey/dub/blob/main/LICENSE.md).
