### ISSUE TITLE
Note date / time format on API + better error handling/

### ISSUE THREAD

**Issue by temrb** [steven-tey/dub#468]
<img width="493" alt="Screenshot 2023-11-16 at 4 28 39 PM" src="https://github.com/steven-tey/dub/assets/22056864/ec721458-15cf-423e-815b-274a9ef8bc2c">

On the documentation, it says just string for date and time.

 Error handling just shows 500 server without where the issue is comming from if you enter in wrong format other than UTC

**Comment by steven-tey** [comment]
Great catch, thanks for filing this @temrb! Just pushed up a fix for it (process it on the backend + add error messages for invalid values + docs)
