### ISSUE TITLE
[BUG]: The GitHub stars are not rendering

### ISSUE THREAD

**Issue by tamalCodes** [steven-tey/dub#475]
### Description

As you can see in the image below the GitHub stars are not rendering here, it's plainly showing just `0`, which is not appropriate considering the number of stars that are there at present in the project. There might be some issue with the [fetching stars logic in this file](https://github.com/steven-tey/dub/blob/main/apps/web/lib/github.ts), or maybe the `getRepos` function hasn't been used anywhere.

I tried looking for the function in the code, but couldn't find any.

### Screenshot

![image](https://github.com/steven-tey/dub/assets/72851613/42bf604e-005f-4bca-8717-2973317998b2)

**Comment by steven-tey** [comment]
Good catch, pushing up a fix for this now! Thanks for the headsup!
