### ISSUE TITLE
 Inquiry About Open Sourcing Files

### ISSUE THREAD

**Issue by mimalef70** [steven-tey/dub#477]
Hi Steven,

I trust you're doing well. I'm reaching out to confirm whether the files for the Home page (https://dub.co/), the Globe section within the Home page, and other pages such as "change log" and "help" have been open-sourced. Your clarification on this matter would be greatly appreciated.

**Comment by steven-tey** [comment]
Hi @mimalef70 – those pages are not open-sourced. Sorry about that!

**Comment by steven-tey** [comment]
Hi @mimalef70 – those pages are not open-sourced.
