### ISSUE TITLE
option to customise dub rich embeds

### ISSUE THREAD

**Issue by BirbEXE** [steven-tey/dub#481]
for platforms like discord, it'd be cool if you had the option to customise the embeds that show for each link (images text etc) through custom meta tags for each link.

**Comment by steven-tey** [comment]
you should be able to using our [Custom Social Media Cards](https://dub.co/help/article/how-to-create-link#custom-social-media-cards) feature! Will close this for now, but feel free to reopen it if it doesn't work!
