### ISSUE TITLE
Leaked API key?

### ISSUE THREAD

**Issue by aryanprince** [steven-tey/dub#492]
Is this an API key or something else? I'm unfamiliar with Crisp but it does look like one.

https://github.com/steven-tey/dub/blob/e4cb50535d202700a0b3259c0572b02ad5d4f537/apps/web/ui/layout/user-dropdown.tsx#L19-L23

**Comment by steven-tey** [comment]
This should be fine since it's not an API key but rather the [unique website identifier](https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/npm/#basic-implementation).

Might obfuscate this into `NEXT_PUBLIC_CRISP_ID` in the future, but for now it's safe to leave it there.

Thanks!
