### ISSUE TITLE
Popup box disappear when you interact with it

### ISSUE THREAD

**Issue by developedbytoby** [steven-tey/dub#52]
Every time I interact with the project creation and popup, it disappears. (Below is a screen recording of what's happening). The browser I'm using is Arc, however I also run into the same problem using Safari. Please let me know if you want anymore information, and I'd be happy to help! :D

https://user-images.githubusercontent.com/77097223/193403190-f5dd89a1-5e8f-472e-b81b-4c617b65f34d.mov

**Comment by developedbytoby** [comment]
Ah! Just noticed, PR #51 fixes issue.

**Comment by steven-tey** [comment]
Ahh yes I was a dumbass and added `onClick={() => closeModal()}` to the modal itself (and not the backdrop)! Just removed that erroneous line so it should work now! Sorry for the inconvenience!

**Comment by developedbytoby** [comment]
It's working! :D

**Comment by steven-tey** [comment]
Yay!! Thanks again for the bug report!

**Comment by developedbytoby** [comment]
No worries, glad to have helped! :)
