### ISSUE TITLE
Greetings Never Received

### ISSUE THREAD

**Issue by theabhayprajapati** [steven-tey/dub#58]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/88815641/193456526-7d6557ad-abf0-4ad8-85e0-99e54be5ec7d.png">

hey @steven-tey I was setting **dub** on my local machine everything worked fine but this isn't whenever I try to Sign Up it gives me this error.
can you please help me with this?

**Comment by theabhayprajapati** [comment]
Got Fixed Now I can Start Contributing to this project 🥳.
 
![image](https://user-images.githubusercontent.com/88815641/193458983-db5dc9a3-a3d8-4d2e-9bc1-b639ae362081.png)


I tried destructing the values for the email server as it was shown on the [next-auth page](https://next-auth.js.org/providers/email#configuration).

**Comment by steven-tey** [comment]
Sorry about the error 😅 glad you were able to figure it out! Feel free to make a PR to add comments/improvements so that folks don't run into a similar issue in the future!
