### ISSUE TITLE
Feature Request: Traffic by source

### ISSUE THREAD

**Issue by ferminrp** [steven-tey/dub#60]
It would be great to understand where a link is being used.

I think [simpleanalytics](https://simpleanalytics.com/simpleanalytics.com) is a good benchmark on how to show this.

![image](https://user-images.githubusercontent.com/21282919/193880070-7d92c1ec-f394-459d-b36c-87ce6c716cb7.png)

**Comment by steven-tey** [comment]
Great idea! I'm [already tracking the `referer` stats](https://github.com/steven-tey/dub/blob/bfc21a1212e7c7b51ef2cf33fbc1064ad18a1b3a/lib/upstash.ts#L96), just need to find a way to display that on the stats page! Will keep you posted on this! :)
