### ISSUE TITLE
Unable to store user session while development.

### ISSUE THREAD

**Issue by theabhayprajapati** [steven-tey/dub#64]
Hello, I did the local setup and while testing it locally I noticed that I was not able to store the user session

# What actually occurred?
1. I get a magic link like this when I sign up or log in.
2. Once I get it, I click on it and it redirects me to localhost:3000 where I can access the dashboard.
3. When I click on it, it takes me to **app.dub.sh** 🤔
4. I am again prompted to log in / sign in if I go straight to the app.localhost:3000.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/88815641/194112312-6cd2c1ea-ca04-412f-8349-fb05a0c42eb7.png">
<img width="193" alt="image" src="https://user-images.githubusercontent.com/88815641/194113891-7a0f2696-b83d-4a23-ae7b-d9349d9dfbbb.png">

**Comment by itsmingjie** [comment]
+1. Current workaround is copying the `next-auth.session-token` manually from `app.locahost` to `localhost:3000`. Seems like localhost does not allow cross site cookies

**Comment by steven-tey** [comment]
Ahh yes, I should've been more clear about this in the setup instructions – I did write a note [here](https://github.com/steven-tey/dub/blob/main/pages/api/auth/%5B...nextauth%5D.tsx#L32) but it can be a bit confusing setting this up locally!

Will improve this very soon but adding better contributing/self-hosting instructions

**Comment by steven-tey** [comment]
Closing this for now – we've updated the self-hosting guide (re: #12) so feel free to try it again and let me know if it still doesn't work!
