### ISSUE TITLE
Bug Allowing for Spaces in URLS

### ISSUE THREAD

**Issue by Soft-Bred** [steven-tey/dub#7]
The url bar allows you to insert any character including spaces which doesn't work in just redirect to the main page.

<img width="477" alt="No 004838@2x" src="https://user-images.githubusercontent.com/60551230/191791136-98a31632-c53b-49cb-bae5-8f2da5c8bc27.png">

**Comment by steven-tey** [comment]
Thanks for the bug report! This should've been fixed with https://github.com/steven-tey/dub/pull/29
