### ISSUE TITLE
Bug allowing emoji is in the URL Bar though they do not work when clicked

### ISSUE THREAD

**Issue by Soft-Bred** [steven-tey/dub#8]
![No 004839@2x](https://user-images.githubusercontent.com/60551230/191791645-924da711-270f-4d19-a21c-41028f4e9d07.png)

when accessing https://dub.sh/🍞, it just takes you to the homepage

**Comment by steven-tey** [comment]
Thanks for the bug report! This should've been fixed with https://github.com/steven-tey/dub/pull/29
