### ISSUE TITLE
BlurImage is too big + reduce screen real estate for link cards

### ISSUE THREAD

**Issue by steven-tey** [steven-tey/dub#80]
> blur is too big and bugs here and there, as you can see in the second link’s image
> 
> ![CleanShot 2022-10-15 at 20 57 32](https://user-images.githubusercontent.com/28986134/196014268-186e1954-2252-4edb-9937-799614644d1a.png)
> 
> also, wouldn’t it be better to add like a dropdown with cats instead of these big buttons? i know those have a confirmation modal, but maybe for a user who has lots of links it’s easier to browse through them by removing that space

h/t to @smonolo for the feedback!

**Comment by steven-tey** [comment]
Rolling this out in #78! 

![CleanShot 2022-10-20 at 08 20 22](https://user-images.githubusercontent.com/28986134/196959972-c9add687-e5d0-4134-a8d7-859287e1fc5a.png)

**Comment by smonolo** [comment]
@steven-tey this looks sick! awesome work

**Comment by steven-tey** [comment]
@smonolo thanks man!! still running a few tests but should be able to merge this by today/tomorrow! 🤞 

BTW does the blur image never resolve? Does it always stay blurred for you?

**Comment by steven-tey** [comment]
oh interesting, thanks for letting me know! will investigate this a bit more! :)

**Comment by steven-tey** [comment]
This should be fixed with #78 🥳
