### ISSUE TITLE
Stats page is `undefined` on "My Dub.sh Links" page

### ISSUE THREAD

**Issue by max-programming** [steven-tey/dub#84]
## Problem
Just noticed that when I hover over the stats button the link has `undefined` in it. 

![image](https://user-images.githubusercontent.com/51731966/197410220-5679f87c-4991-48e1-84fa-b8b1e6e24d3e.png)

## Cause

In [this code](https://github.com/steven-tey/dub/blob/73c74617f5bd8efdfdf687eb8e77021cdb4f3b6f/components/app/links/link-card.tsx#L115), the `href` has `slug` in it which is only available in **Projects** and not in normal `dub.sh` links. That's why there is no stats page for normal links and still it shows
![image](https://user-images.githubusercontent.com/51731966/197410258-6a419086-b248-4d39-bc68-65a0b3bfe3b3.png)

**Comment by max-programming** [comment]
Just noticed that there is a stats page for normal links. If we go to `https://dub.sh/stats/[linkslug]`, it works.

I'll fix this issue

**Comment by steven-tey** [comment]
Oh yes, sorry about this! It was fixed a couple of days ago – thank you for the heads-up anyways! 🙏
