### ISSUE TITLE
Curl Support

### ISSUE THREAD

**Issue by TomBener** [steven-tey/dub#89]
It is very convenient to use [TinyURL](https://tinyurl.com) via [Curl](https://curl.se) on the command line:

```shell
curl -s tinyurl.com/api-create.php?url=<link>
```

And it would be great if dub has the similar feature! And here are more [examples](https://github.com/chubin/awesome-console-services#URL-Shortener).

**Comment by steven-tey** [comment]
Related to #73, thanks for the feature request! I'm planning to work on an API for Dub (will probably need user signup + an Authorization header though to prevent spam). Will keep you posted on this!

**Comment by steven-tey** [comment]
Closing this because it's a duplicate of #73 – feel free to follow that one instead!
