### ISSUE TITLE
z-index visual bug in stats component

### ISSUE THREAD

**Issue by MatthewStanciu** [steven-tey/dub#9]
<img width="927" alt="Screen Shot 2022-09-22 at 12 06 21 PM" src="https://user-images.githubusercontent.com/14811170/191797290-ec2e44b1-ccbf-4731-9b65-2797be0b203a.png">

![IMG_163532364CC3-1](https://user-images.githubusercontent.com/14811170/191797454-38bee1ce-5f96-4e57-9fc7-73aa0527e221.jpeg)

When I view the stats page with the console open or on my phone, the countries display on top of the header, which looks broken.

**Comment by MatthewStanciu** [comment]
Had to step away from my computer but I’ll open a PR to fix when I’m back if no one else tackles it by then!

**Comment by steven-tey** [comment]
Fixed with #50! 😌
